import { webMethod, Permissions } from 'wix-web-module';
import { isUuid, requireInternalAgent, text, writeInternalAudit } from '../RIA/internalAccess.js';
import { restRequest } from '../RIA/supabaseServer.js';

function now() { return new Date().toISOString(); }
function key() { return `POL-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`; }
function policyMap(row = {}) { const payload = row.payload && typeof row.payload === 'object' ? row.payload : {}; return { id: row.id || '', policyId: row.entity_id || row.id || '', title: row.title || '', body: row.body || '', fileUrl: row.file_url || '', status: row.status || 'DRAFT', active: row.active === true, payload, ...payload }; }
async function access() { return requireInternalAgent({ capability: 'manage' }); }
async function find(input = {}) { const id = text(input.id || input.policyId || input.entityId, 160); if (!id) return null; const query = isUuid(id) ? { select: '*', id: `eq.${id}`, limit: 1 } : { select: '*', entity_id: `eq.${id}`, limit: 1 }; const rows = await restRequest({ table: 'policy_documents', query }); return rows?.[0] || null; }
async function audit(agent, action, target, after = {}) { await writeInternalAudit({ agent, action: `POLICY_${action}`, target, after }).catch(() => null); }

export const listPolicyDocuments = webMethod(Permissions.SiteMember, async () => {
  await access(); const rows = await restRequest({ table: 'policy_documents', query: { select: '*', order: 'updated_at.desc', limit: 1000 } }); return { ok: true, policies: (rows || []).map(policyMap) };
});
export const getPolicyDocument = webMethod(Permissions.SiteMember, async (input = {}) => { await access(); const row = await find(input); if (!row) throw new Error('POLICY_NOT_FOUND'); return { ok: true, policy: policyMap(row) }; });
export const getPolicyControlBootstrap = webMethod(Permissions.SiteMember, async () => { const { profile } = await access(); const list = await listPolicyDocuments({}); return { ...list, profile, apps: [] }; });
export const savePolicyDocument = webMethod(Permissions.SiteMember, async (input = {}) => {
  const { agent } = await access(); const policy = input.policy || input.item || input; const existing = await find(policy); const policyId = text(policy.policyId || policy.entityId || existing?.entity_id, 160) || key(); const body = { title: text(policy.title, 500) || 'Untitled policy', entity_id: policyId, status: text(policy.status || existing?.status || 'DRAFT', 80).toUpperCase(), body: text(policy.body || policy.content, 50000) || null, file_url: /^https:\/\//i.test(text(policy.fileUrl || policy.file_url, 2000)) ? text(policy.fileUrl || policy.file_url, 2000) : null, active: policy.active !== false, payload: { ...(existing?.payload || {}), ...policy, policyId }, updated_at: now() }; const rows = existing ? await restRequest({ table: 'policy_documents', method: 'PATCH', query: { id: `eq.${existing.id}` }, body }) : await restRequest({ table: 'policy_documents', method: 'POST', body: { ...body, created_at: now() } }); const saved = rows?.[0] || existing; await audit(agent, 'SAVED', saved?.id, { policyId }); return { ok: true, policy: policyMap(saved || {}) };
});
export const publishPolicyDocument = webMethod(Permissions.SiteMember, async (input = {}) => { const { agent } = await access(); const row = await find(input); if (!row) throw new Error('POLICY_NOT_FOUND'); const rows = await restRequest({ table: 'policy_documents', method: 'PATCH', query: { id: `eq.${row.id}` }, body: { status: 'PUBLISHED', active: true, payload: { ...(row.payload || {}), publishedAt: now() }, updated_at: now() } }); const saved = rows?.[0] || row; await audit(agent, 'PUBLISHED', saved.id); return { ok: true, policy: policyMap(saved) }; });
export const archivePolicyDocument = webMethod(Permissions.SiteMember, async (input = {}) => { const { agent } = await access(); const row = await find(input); if (!row) throw new Error('POLICY_NOT_FOUND'); const rows = await restRequest({ table: 'policy_documents', method: 'PATCH', query: { id: `eq.${row.id}` }, body: { status: 'ARCHIVED', active: false, updated_at: now() } }); const saved = rows?.[0] || row; await audit(agent, 'ARCHIVED', saved.id); return { ok: true, policy: policyMap(saved) }; });
export const savePolicyAttachment = webMethod(Permissions.SiteMember, async (input = {}) => { const { agent } = await access(); const attachment = input.attachment || input; const row = await find(attachment); if (!row) throw new Error('POLICY_NOT_FOUND'); const fileUrl = text(attachment.fileUrl || attachment.url, 2000); if (fileUrl && !/^https:\/\//i.test(fileUrl)) throw new Error('POLICY_ATTACHMENT_URL_INVALID'); const payload = { ...(row.payload || {}), attachments: [...(Array.isArray(row.payload?.attachments) ? row.payload.attachments : []), { ...attachment, fileUrl, savedAt: now() }] }; const rows = await restRequest({ table: 'policy_documents', method: 'PATCH', query: { id: `eq.${row.id}` }, body: { file_url: fileUrl || row.file_url || null, payload, updated_at: now() } }); const saved = rows?.[0] || row; await audit(agent, 'ATTACHMENT_SAVED', saved.id); return { ok: true, policy: policyMap(saved) }; });
