import { webMethod, Permissions } from 'wix-web-module';
import { isUuid, requireInternalAgent, text, writeInternalAudit } from './RIA/internalAccess.js';
import { restRequest } from './RIA/supabaseServer.js';

function now() { return new Date().toISOString(); }
function docMap(row = {}) { const payload = row.payload && typeof row.payload === 'object' ? row.payload : {}; return { id: row.id || '', documentId: row.id || row.document_number || '', documentNumber: row.document_number || '', title: payload.title || row.document_type || 'Document', categoryId: payload.categoryId || '', documentType: row.document_type || '', status: row.status || 'DRAFT', fileUrl: row.pdf_url || '', issuedAt: row.issued_at || '', payload, ...payload }; }
async function access() { return requireInternalAgent({ capability: 'manage' }); }
async function findDocument(input = {}) { const id = text(input.documentId || input.id, 160); if (!id) return null; const query = isUuid(id) ? { select: '*', id: `eq.${id}`, limit: 1 } : { select: '*', document_number: `eq.${id}`, limit: 1 }; const rows = await restRequest({ table: 'altea_documents', query }); return rows?.[0] || null; }
async function audit(agent, action, target, after = {}) { await writeInternalAudit({ agent, action: `DOCUNET_${action}`, target, after }).catch(() => null); }

export const getDocAdminBootstrap = webMethod(Permissions.SiteMember, async () => {
  const { profile } = await access(); const [documents, categories] = await Promise.all([restRequest({ table: 'altea_documents', query: { select: '*', order: 'updated_at.desc', limit: 1000 } }), restRequest({ table: 'document_templates', query: { select: '*', order: 'title.asc', limit: 500 } })]); return { ok: true, profile, documents: (documents || []).map(docMap), categories: (categories || []).map((row) => ({ id: row.id, categoryId: row.entity_id || row.id, title: row.title || '', status: row.status || '', active: row.active !== false, payload: row.payload || {} })), apps: [] };
});

export const searchDocAdminDocuments = webMethod(Permissions.SiteMember, async (input = {}) => { await access(); const filters = input.filters || input; const query = text(filters.query || filters.search, 240).toLowerCase(); const status = text(filters.status, 80).toUpperCase(); const rows = await restRequest({ table: 'altea_documents', query: { select: '*', order: 'updated_at.desc', limit: 2000 } }); const documents = (rows || []).map(docMap).filter((document) => (!status || document.status.toUpperCase() === status) && (!query || `${document.title} ${document.documentNumber} ${document.documentType} ${document.status}`.toLowerCase().includes(query))); return { ok: true, documents };
});

async function saveDocument(metadata = {}, file = null) {
  const { agent } = await access(); const existing = await findDocument(metadata); const title = text(metadata.title || metadata.name, 500) || 'Untitled document'; const status = text(metadata.publishStatus || metadata.status || existing?.status || 'DRAFT', 80).toUpperCase(); const documentNumber = text(metadata.documentNumber || metadata.documentId || existing?.document_number, 160) || `DOC-${Date.now()}`; const body = { document_type: text(metadata.documentType || metadata.type || existing?.document_type || 'GENERAL', 160), document_number: documentNumber, status, pdf_url: text(file?.fileUrl || metadata.fileUrl || existing?.pdf_url, 2000) || null, issued_at: status === 'PUBLISHED' ? now() : existing?.issued_at || null, issued_by_agent_user_id: agent.id, payload: { ...(existing?.payload || {}), ...metadata, title, categoryId: metadata.categoryId || existing?.payload?.categoryId || '', file: file || existing?.payload?.file || null }, updated_at: now() };
  const rows = existing ? await restRequest({ table: 'altea_documents', method: 'PATCH', query: { id: `eq.${existing.id}` }, body }) : await restRequest({ table: 'altea_documents', method: 'POST', body: { ...body, created_at: now() } }); const saved = rows?.[0] || existing; await audit(agent, 'DOCUMENT_SAVED', saved?.id, { status, hasFile: Boolean(file) }); return { ok: true, document: docMap(saved || {}) };
}
export const adminSaveDocumentWithFile = webMethod(Permissions.SiteMember, async (input = {}) => saveDocument(input.metadata || {}, input.file || null));
export const adminSaveDocumentMetadata = webMethod(Permissions.SiteMember, async (input = {}) => saveDocument(input.metadata || input, null));
export const adminSetDocumentStatus = webMethod(Permissions.SiteMember, async (input = {}) => { const metadata = { documentId: input.documentId, publishStatus: input.publishStatus || input.status }; return saveDocument(metadata, null); });
export const adminDeleteDocument = webMethod(Permissions.SiteMember, async (input = {}) => { const { agent } = await access(); const row = await findDocument(input); if (!row) throw new Error('DOCUNET_DOCUMENT_NOT_FOUND'); const rows = await restRequest({ table: 'altea_documents', method: 'PATCH', query: { id: `eq.${row.id}` }, body: { status: 'ARCHIVED', updated_at: now() } }); const saved = rows?.[0] || row; await audit(agent, 'DOCUMENT_ARCHIVED', saved.id); return { ok: true, document: docMap(saved) }; });
export const adminSaveCategory = webMethod(Permissions.SiteMember, async (input = {}) => { const { agent } = await access(); const category = input.category || input; const id = text(category.id || category.categoryId || category.entityId, 160); const existing = id ? (await restRequest({ table: 'document_templates', query: { select: '*', [isUuid(id) ? 'id' : 'entity_id']: `eq.${id}`, limit: 1 } }))[0] : null; const body = { title: text(category.title || category.name, 500) || 'Untitled category', entity_id: text(category.categoryId || category.entityId || existing?.entity_id, 160) || `CATEGORY-${Date.now()}`, status: text(category.status || 'ACTIVE', 80), body: text(category.description, 10000) || null, active: category.active !== false, payload: { ...(existing?.payload || {}), ...category }, updated_at: now() }; const rows = existing ? await restRequest({ table: 'document_templates', method: 'PATCH', query: { id: `eq.${existing.id}` }, body }) : await restRequest({ table: 'document_templates', method: 'POST', body: { ...body, created_at: now() } }); const saved = rows?.[0] || existing; await audit(agent, 'CATEGORY_SAVED', saved?.id); return { ok: true, category: saved || null }; });
export const adminDeleteCategory = webMethod(Permissions.SiteMember, async (input = {}) => { const { agent } = await access(); const id = text(input.categoryId || input.id, 160); if (!id) throw new Error('DOCUNET_CATEGORY_REQUIRED'); const query = isUuid(id) ? { id: `eq.${id}` } : { entity_id: `eq.${id}` }; const rows = await restRequest({ table: 'document_templates', method: 'PATCH', query, body: { active: false, status: 'ARCHIVED', updated_at: now() } }); await audit(agent, 'CATEGORY_ARCHIVED', id); return { ok: true, category: rows?.[0] || null }; });
export const adminSearchAudit = webMethod(Permissions.SiteMember, async (input = {}) => { await access(); const filters = input.filters || {}; const rows = await restRequest({ table: 'admin_audit_logs', query: { select: 'id,log_id,admin_id,target_member,action_performed,created_at', order: 'created_at.desc', limit: Math.min(Math.max(Number(filters.limit) || 500, 1), 1000) } }); const q = text(filters.query, 160).toLowerCase(); return { ok: true, audit: (rows || []).filter((row) => !q || `${row.log_id} ${row.action_performed} ${row.target_member}`.toLowerCase().includes(q)) }; });
