// /src/backend/SKANDI_CORE/groupTalk.web.js
import { webMethod, Permissions } from "@wix/web-methods";
import * as core from "backend/SKANDI_CORE/groupTalk";
const member = (fn) => webMethod(Permissions.Anyone, async (input = {}) => fn(input));
export const getGroupTalkBootstrap = member(core.getGroupTalkBootstrapCore);
export const getGroupTalkRealtimeConfig = member(core.getGroupTalkRealtimeConfigCore);
export const updateGroupTalkPresence = member(core.updateGroupTalkPresenceCore);
export const getGroupTalkPresence = member(core.getGroupTalkPresenceCore);
export const createLiveKitToken = member(core.createLiveKitTokenCore);
export const triggerGroupTalkEvent = member(core.triggerGroupTalkEventCore);
export const getPhoneBook = member(core.getPhoneBookCore);
export const sendLocationPing = member(core.sendLocationPingCore);
export const getLiveLocations = member(core.getLiveLocationsCore);
export const createGroupTalkTicket = member(core.createGroupTalkTicketCore);
export const getGroupTalkTickets = member(core.getGroupTalkTicketsCore);
export const replyToGroupTalkTicket = member(core.replyToGroupTalkTicketCore);
export const searchGroupTalkHistory = member(core.searchGroupTalkHistoryCore);
export const adminSaveGroup = member(core.adminSaveGroupCore);
export const adminSetMembership = member(core.adminSetMembershipCore);
export const getTicketCategories = member(core.getTicketCategoriesCore);
export const saveTicketCategory = member(core.saveTicketCategoryCore);
export const deleteTicketCategory = member(core.deleteTicketCategoryCore);
