// /src/backend/SKANDI_CORE/groupTalk.js
// SKANDI GroupTalk canonical business core — Supabase PostgreSQL + Supabase Realtime + LiveKit.
// Pusher is retired. Staff identity comes only from staffAuth; Supabase credentials come only from supabaseServer.

import { secrets } from "wix-secrets-backend.v2";
import { elevate } from "wix-auth";
import { AccessToken } from "livekit-server-sdk";
import { restRequest, getSupabaseRealtimeBrowserConfig, realtimeBroadcast } from "backend/SKANDI_CORE/supabaseServer.js";
import { requireStaffPortalSessionCore } from "backend/SKANDI_CORE/staffAuth.js";

const getSecretValue = elevate(secrets.getSecretValue);
const T = Object.freeze({
  groups:"grouptalk_groups", members:"grouptalk_group_members", phonebook:"grouptalk_phonebook",
  categories:"grouptalk_ticket_categories", tickets:"grouptalk_tickets", replies:"grouptalk_ticket_replies",
  locations:"grouptalk_locations", history:"grouptalk_history", sessions:"grouptalk_realtime_sessions", audit:"grouptalk_audit"
});
const DEFAULT_CATEGORIES = [["bus-manifest","Bus Manifest"],["guest-issue","Guest Issue"],["hotel-issue","Hotel Issue"],["transfer-issue","Transfer Issue"],["flight-disruption","Flight Disruption"],["emergency-support","Emergency Support"],["documents","Documents"],["schedule-change","Schedule Change"],["lost-item","Lost Item"],["operations-question","Operations Question"],["other","Other"]];
const ALLOWED_EVENTS = new Set(["PTT_DOWN","PTT_UP","PTT_DOWN_DESKTOP","PTT_UP_DESKTOP","AUDIO_START","AUDIO_STOP","EMERGENCY","GROUP_CHANGED","LIVEKIT_JOIN","PHONE_BOOK_CALL"]);
function clean(v,max=5000){return String(v??"").trim().slice(0,max)}
function lower(v){return clean(v,300).toLowerCase()}
function upper(v){return clean(v,300).toUpperCase()}
function obj(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}}
function arr(v){return Array.isArray(v)?v:[]}
function first(v){return arr(v)[0]||null}
function now(){return new Date().toISOString()}
function rand(n=12){return Math.random().toString(36).slice(2,2+n)}
function slug(v){return clean(v,120).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"group"}
function ticketNumber(){return `GT-${now().slice(0,10).replaceAll("-","")}-${rand(6).toUpperCase()}`}
async function secret(name){try{const r=await getSecretValue(name);return clean(r?.value??r?.secretValue??r,20000)}catch{return ""}}
async function staff(){const s=await requireStaffPortalSessionCore(); if(!s.canAccessGroupTalk&&!s.canManage&&!s.isSystemAdmin) throw new Error("GROUPTALK_ACCESS_DISABLED"); return s}
async function ops(){const s=await staff(); if(!s.canManage&&!s.isSystemAdmin) throw new Error("GROUPTALK_ADMIN_REQUIRED"); return s}
function profile(s){return {...s.profile,canManage:Boolean(s.canManage||s.isSystemAdmin),canAccessGroupTalk:true}}
async function groups(){const r=await restRequest({table:T.groups,query:{select:"*",order:"sort_order.asc",limit:500}});return arr(r).filter(x=>!["archived","deleted","disabled","inactive"].includes(lower(x.status)))}
async function memberships(id){return arr(await restRequest({table:T.members,query:{select:"*",agent_user_id:`eq.${id}`,limit:500}})).filter(x=>!["inactive","removed","revoked","disabled"].includes(lower(x.membership_status)))}
function publicGroup(g,m,p){const gp=obj(g.payload), admin=p.canManage||m?.can_admin===true, listen=m?m.can_listen!==false:true;return {groupId:g.id,id:g.id,groupKey:g.group_key,title:g.name,name:g.name,description:g.description||"",base:gp.base||gp.station||"",category:g.group_type||"Operations",status:g.status||"active",livekitRoomName:g.livekit_room||`grouptalk-${g.group_key}`,defaultGroup:gp.defaultGroup===true,capabilities:{canListen:listen,canTalk:g.can_voice!==false&&listen&&(admin||!m||m.can_talk!==false),canViewLocations:g.can_location!==false&&(admin||!m||m.can_view_locations!==false),canCreateTickets:g.can_ticket!==false&&(admin||!m||m.can_manage_tickets!==false),canAdmin:admin}}}
async function allowedPairs(s){const p=profile(s), gs=await groups(); if(p.canManage)return gs.map(group=>({group,m:null})); const ms=await memberships(p.agentUserId); return gs.map(group=>({group,m:ms.find(x=>x.group_id===group.id||x.group_key===group.group_key)})).filter(x=>x.m||obj(x.group.payload).allowAllStaff===true||["all_staff","staff"].includes(lower(x.group.visibility)))}
async function requireGroup(s,key=""){const pairs=await allowedPairs(s), q=clean(key,160), hit=pairs.find(x=>x.group.id===q||x.group.group_key===q)||(!q?pairs[0]:null); if(!hit)throw new Error("GROUPTALK_GROUP_NOT_ALLOWED"); return {...hit,public:publicGroup(hit.group,hit.m,profile(s))}}
async function topic(group){const p=obj(group.payload); if(p.realtimeTopic)return p.realtimeTopic; const realtimeTopic=`grouptalk:${group.id}:${rand(16)}`; await restRequest({table:T.groups,method:"PATCH",query:{id:`eq.${group.id}`},body:{payload:{...p,realtimeTopic},updated_at:now()},prefer:"return=minimal"}); return realtimeTopic}
async function broadcast(group,event,payload){return realtimeBroadcast({topic:await topic(group),event:"grouptalk",payload:{event,groupId:group.id,groupKey:group.group_key,emittedAt:now(),payload}})}
async function audit(eventType,s,{group=null,entityTable=null,entityId=null,ticketNo=null,payload={}}={}){const p=profile(s);await restRequest({table:T.audit,method:"POST",body:{event_type:eventType,entity_table:entityTable,entity_id:entityId,group_key:group?.group_key||null,ticket_number:ticketNo,source:"wix-grouptalk",payload,created_by_agent_user_id:p.agentUserId,created_by_name:p.displayName||p.fullName,created_at:now()},prefer:"return=minimal"}).catch(()=>null)}
async function history(eventType,s,{group=null,ticketNo=null,message=null,payload={}}={}){const p=profile(s);await restRequest({table:T.history,method:"POST",body:{event_type:eventType,group_key:group?.group_key||null,actor_agent_user_id:p.agentUserId,actor_sk_id:p.skId,actor_name:p.displayName||p.fullName,ticket_number:ticketNo,message,payload,created_at:now()},prefer:"return=minimal"}).catch(()=>null)}
function publicCategory(r){return {categoryId:r.category_key,id:r.category_key,title:r.label,name:r.label,label:r.label,description:r.description||"",active:r.is_active!==false,sort:Number(r.sort_order||100),priorityDefault:r.priority_default||"normal",slaMinutes:Number(r.sla_minutes||1440)}}
async function categoryRows(all=false){const q={select:"*",order:"sort_order.asc",limit:500};if(!all)q.is_active="eq.true";return arr(await restRequest({table:T.categories,query:q}))}
async function ensureCategories(s){let rows=await categoryRows(true);if(rows.length)return rows;const p=profile(s);await restRequest({table:T.categories,method:"POST",query:{on_conflict:"category_key"},body:DEFAULT_CATEGORIES.map(([category_key,label],i)=>({category_key,label,priority_default:"normal",sla_minutes:1440,is_active:true,sort_order:(i+1)*10,payload:{},created_by_agent_user_id:p.agentUserId,created_at:now(),updated_at:now()})),prefer:"resolution=ignore-duplicates,return=minimal"});return categoryRows(true)}
async function phonebook(){const rows=arr(await restRequest({table:T.phonebook,query:{select:"*",is_visible:"eq.true",order:"display_name.asc",limit:1000}}));return rows.map(r=>({name:r.display_name,skId:r.sk_id||"",role:r.position||r.department||"",base:r.base||r.station||"",phone:r.phone||r.extension||"",email:r.email||"",status:r.presence_status||r.availability_status||"offline",avatarUrl:r.avatar_url||""}))}
function publicTicket(r){const p=obj(r.payload);return {ticketId:r.id,id:r.id,ticketNumber:r.ticket_number,category:r.category_key,groupId:r.group_id,groupKey:r.group_key,subject:r.title,title:r.title,message:r.description||"",status:upper(r.status||"open"),priority:r.priority||"normal",requesterAgentId:r.requester_agent_user_id,requesterSkId:r.requester_sk_id||"",requesterName:r.requester_name||"",requesterEmail:r.requester_email||"",routeRef:p.routeRef||"",caseMode:p.caseMode===true,targetSkIds:arr(p.targetSkIds),employees:arr(p.employees),locationLabel:r.location_label||"",latitude:r.latitude,longitude:r.longitude,createdAt:r.created_at,updatedAt:r.updated_at,closedAt:r.closed_at}}
function publicReply(r){return {id:r.id,ticketId:r.ticket_id,ticketNumber:r.ticket_number,body:r.body,senderRole:r.reply_type||"STAFF",senderSkId:r.author_sk_id||"",senderName:r.author_name||"",isInternal:r.is_internal!==false,createdAt:r.created_at,payload:obj(r.payload)}}

export async function getGroupTalkBootstrapCore(){const s=await staff(),p=profile(s), pairs=await allowedPairs(s), cats=await ensureCategories(s); const gs=pairs.map(x=>publicGroup(x.group,x.m,p)), active=gs.find(x=>x.defaultGroup)||gs[0]||null; const q={select:"*",order:"updated_at.desc",limit:200};if(!p.canManage)q.requester_agent_user_id=`eq.${p.agentUserId}`;return {ok:true,provider:"SUPABASE",realtimeProvider:"SUPABASE_REALTIME",voiceProvider:"LIVEKIT",profile:p,apps:s.apps||[],groups:gs,activeGroupId:active?.groupId||"",phonebook:await phonebook(),tickets:arr(await restRequest({table:T.tickets,query:q})).map(publicTicket),ticketCategories:cats.filter(x=>x.is_active!==false).map(publicCategory),config:{realtimeProvider:"SUPABASE_REALTIME",voiceProvider:"LIVEKIT",mapProvider:"OPENFREEMAP",presenceProvider:"SUPABASE_REALTIME_SESSIONS"},canManage:p.canManage}}
export async function getGroupTalkRealtimeConfigCore({groupId=""}={}){const s=await staff(),{group,public:g}=await requireGroup(s,groupId), browser=await getSupabaseRealtimeBrowserConfig(),p=profile(s),sessionKey=`GT-RT-${rand(24)}`,t=await topic(group);await restRequest({table:T.sessions,method:"POST",body:{session_key:sessionKey,agent_user_id:p.agentUserId,sk_id:p.skId,display_name:p.displayName||p.fullName,livekit_room:g.livekitRoomName,livekit_identity:`${p.skId||p.agentUserId}-${rand(8)}`,status:"online",joined_at:now(),payload:{groupId:group.id,groupKey:group.group_key,topic:t,role:p.role,base:p.base},created_at:now(),updated_at:now()},prefer:"return=minimal"});return {ok:true,provider:"SUPABASE_REALTIME",supabaseUrl:browser.url,publishableKey:browser.publishableKey,topic:t,broadcastEvent:"grouptalk",sessionKey,groupId:g.groupId,groupKey:g.groupKey}}
export async function updateGroupTalkPresenceCore({groupId="",sessionKey="",status="online"}={}){const s=await staff(),p=profile(s),{group}=await requireGroup(s,groupId);const key=clean(sessionKey,240);if(!key)throw new Error("GROUPTALK_REALTIME_SESSION_REQUIRED");const row=first(await restRequest({table:T.sessions,query:{select:"*",session_key:`eq.${key}`,agent_user_id:`eq.${p.agentUserId}`,limit:1}}));if(!row)throw new Error("GROUPTALK_REALTIME_SESSION_NOT_FOUND");const next=lower(status)==="offline"?"offline":"online";await restRequest({table:T.sessions,method:"PATCH",query:{id:`eq.${row.id}`},body:{status:next,left_at:next==="offline"?now():null,updated_at:now()},prefer:"return=minimal"});await broadcast(group,"presence-updated",{agentUserId:p.agentUserId,skId:p.skId,name:p.displayName,state:next}).catch(()=>null);return {ok:true,status:next}}
export async function getGroupTalkPresenceCore({groupId=""}={}){const s=await staff(),{group}=await requireGroup(s,groupId),cutoff=new Date(Date.now()-70000).toISOString();const rows=arr(await restRequest({table:T.sessions,query:{select:"*",status:"eq.online",updated_at:`gte.${cutoff}`,order:"updated_at.desc",limit:1000}}));return {ok:true,members:rows.filter(r=>{const p=obj(r.payload);return p.groupId===group.id||p.groupKey===group.group_key}).map(r=>({id:r.agent_user_id||r.session_key,agentUserId:r.agent_user_id,skId:r.sk_id||"",name:r.display_name||r.sk_id||"Staff",role:obj(r.payload).role||"",base:obj(r.payload).base||"",state:"online",updatedAt:r.updated_at}))}}
export async function createLiveKitTokenCore({groupId=""}={}){const s=await staff(),p=profile(s),{group,public:g}=await requireGroup(s,groupId);if(!g.capabilities.canListen)throw new Error("GROUPTALK_AUDIO_LISTEN_DISABLED");const [apiKey,apiSecret,livekitUrl]=await Promise.all([secret("LIVEKIT_API_KEY"),secret("LIVEKIT_API_SECRET"),secret("LIVEKIT_URL")]);if(!apiKey||!apiSecret||!livekitUrl)throw new Error("LIVEKIT_SECRETS_MISSING");const room=g.livekitRoomName,identity=`${p.skId||p.agentUserId}-${rand(8)}`,token=new AccessToken(apiKey,apiSecret,{identity,name:p.displayName||p.fullName,ttl:"15m",metadata:JSON.stringify({skId:p.skId,role:p.role,base:p.base,groupId:group.id,provider:"SKANDI_GROUPTALK"})});token.addGrant({roomJoin:true,room,canSubscribe:true,canPublish:g.capabilities.canTalk,canPublishData:true});return {ok:true,token:await token.toJwt(),livekitUrl,room,roomName:room,identity,groupId:group.id,canPublishAudio:g.capabilities.canTalk,canSubscribe:true}}
export async function triggerGroupTalkEventCore(payload={}){const s=await staff(),p=profile(s),type=upper(payload.type||"EVENT");if(!ALLOWED_EVENTS.has(type))throw new Error("GROUPTALK_EVENT_NOT_ALLOWED");const {group,public:g}=await requireGroup(s,payload.groupId||payload.group);if((type.includes("PTT_DOWN")||type.includes("AUDIO_START"))&&!g.capabilities.canTalk)throw new Error("GROUPTALK_TALK_DISABLED");const data={type,groupId:group.id,groupKey:group.group_key,skId:p.skId,name:p.displayName||p.fullName,role:p.role,base:p.base,targetSkId:clean(payload.targetSkId,80)||null,targetName:clean(payload.targetName,160)||null,targetPhone:clean(payload.targetPhone,80)||null,priority:clean(payload.priority,40)||null,createdAt:now()};const event=type==="EMERGENCY"?"emergency-alert":type.includes("PTT_DOWN")||type.includes("AUDIO_START")?"ptt-started":type.includes("PTT_UP")||type.includes("AUDIO_STOP")?"ptt-ended":"grouptalk-event";await audit(type,s,{group,payload:data});await history(type,s,{group,message:event,payload:data});return {ok:true,eventType:type,realtime:await broadcast(group,event,data)}}
export async function getPhoneBookCore({groupId=""}={}){const s=await staff();if(groupId)await requireGroup(s,groupId);return {ok:true,contacts:await phonebook()}}
export async function sendLocationPingCore(payload={}){const s=await staff(),p=profile(s),lat=Number(payload.latitude),lng=Number(payload.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error("Valid latitude and longitude are required.");const {group,public:g}=await requireGroup(s,payload.groupId);if(!g.capabilities.canViewLocations)throw new Error("GROUPTALK_LOCATION_DISABLED");const stamp=now(), rows=await restRequest({table:T.locations,method:"POST",query:{on_conflict:"agent_user_id"},body:{agent_user_id:p.agentUserId,sk_id:p.skId,display_name:p.displayName||p.fullName,latitude:lat,longitude:lng,accuracy_meters:Number(payload.accuracy)||null,heading:Number(payload.heading)||null,speed:Number(payload.speed)||null,source:"browser-geolocation",group_key:group.group_key,last_seen_at:stamp,payload:{role:p.role,base:p.base,groupId:group.id},updated_at:stamp},prefer:"resolution=merge-duplicates,return=representation"});const r=first(rows)||{},location={id:r.id,agentUserId:p.agentUserId,skId:p.skId,name:p.displayName||p.fullName,role:p.role,base:p.base,groupId:group.id,groupKey:group.group_key,latitude:Number(r.latitude??lat),longitude:Number(r.longitude??lng),accuracy:r.accuracy_meters,heading:r.heading,speed:r.speed,lastSeenAt:r.last_seen_at||stamp};await broadcast(group,"location-updated",location);return {ok:true,location}}
export async function getLiveLocationsCore({groupId=""}={}){const s=await staff(),{group,public:g}=await requireGroup(s,groupId);if(!g.capabilities.canViewLocations)return {ok:true,locations:[]};const cutoff=new Date(Date.now()-15*60*1000).toISOString(),rows=arr(await restRequest({table:T.locations,query:{select:"*",group_key:`eq.${group.group_key}`,last_seen_at:`gte.${cutoff}`,order:"last_seen_at.desc",limit:1000}}));return {ok:true,locations:rows.map(r=>({id:r.id,agentUserId:r.agent_user_id,skId:r.sk_id||"",name:r.display_name||r.sk_id||"Staff",role:obj(r.payload).role||"",base:obj(r.payload).base||"",groupId:obj(r.payload).groupId||group.id,groupKey:r.group_key,latitude:Number(r.latitude),longitude:Number(r.longitude),accuracy:r.accuracy_meters,heading:r.heading,speed:r.speed,lastSeenAt:r.last_seen_at}))}}
async function categoryKey(value,s){const wanted=slug(value||"operations-question"),rows=await ensureCategories(s);return rows.find(r=>r.category_key===wanted)?.category_key||"operations-question"}
export async function createGroupTalkTicketCore(payload={}){const s=await staff(),p=profile(s),{group,public:g}=await requireGroup(s,payload.groupId);if(!g.capabilities.canCreateTickets&&!p.canManage)throw new Error("GROUPTALK_TICKET_CREATE_DISABLED");const stamp=now(),cat=await categoryKey(payload.category,s),inserted=first(await restRequest({table:T.tickets,method:"POST",body:{ticket_number:ticketNumber(),category_key:cat,group_id:group.id,group_key:group.group_key,title:clean(payload.subject,240)||"Ops request",description:clean(payload.message,6000),status:"open",priority:lower(payload.priority||"normal"),requester_agent_user_id:p.agentUserId,requester_sk_id:p.skId,requester_name:p.displayName||p.fullName,requester_email:p.email||null,location_label:clean(payload.locationLabel,300)||null,latitude:Number.isFinite(Number(payload.latitude))?Number(payload.latitude):null,longitude:Number.isFinite(Number(payload.longitude))?Number(payload.longitude):null,payload:{routeRef:clean(payload.routeRef,300),caseMode:payload.caseMode===true,createdFrom:clean(payload.createdFrom,120),targetSkIds:arr(payload.targetSkIds).map(v=>clean(v,80)).filter(Boolean),employees:arr(payload.employees).slice(0,100)},created_by_agent_user_id:p.agentUserId,created_at:stamp,updated_at:stamp}}));if(!inserted)throw new Error("GROUPTALK_TICKET_CREATE_FAILED");if(clean(payload.message,6000))await restRequest({table:T.replies,method:"POST",body:{ticket_id:inserted.id,ticket_number:inserted.ticket_number,body:clean(payload.message,6000),author_agent_user_id:p.agentUserId,author_sk_id:p.skId,author_name:p.displayName||p.fullName,reply_type:"staff",is_internal:true,payload:{initial:true},created_at:stamp},prefer:"return=minimal"});const ticket=publicTicket(inserted);await audit("OPS_REQUEST_CREATED",s,{group,entityTable:T.tickets,entityId:inserted.id,ticketNo:inserted.ticket_number,payload:ticket});await history("OPS_REQUEST_CREATED",s,{group,ticketNo:inserted.ticket_number,message:ticket.subject,payload:ticket});await broadcast(group,"ticket-created",{ticket}).catch(()=>null);return {ok:true,ticket}}
export async function getGroupTalkTicketsCore(payload={}){const s=await staff(),p=profile(s),id=clean(payload.ticketId,160);if(id){let row=first(await restRequest({table:T.tickets,query:{select:"*",id:`eq.${id}`,limit:1}}));if(!row)row=first(await restRequest({table:T.tickets,query:{select:"*",ticket_number:`eq.${id}`,limit:1}}));if(!row)throw new Error("Ticket not found.");await requireGroup(s,row.group_id||row.group_key);if(!p.canManage&&row.requester_agent_user_id!==p.agentUserId&&row.requester_sk_id!==p.skId)throw new Error("Not authorized for this ticket.");return {ok:true,ticket:publicTicket(row),messages:arr(await restRequest({table:T.replies,query:{select:"*",ticket_id:`eq.${row.id}`,order:"created_at.asc",limit:500}})).map(publicReply)}}const q={select:"*",order:"updated_at.desc",limit:200};if(payload.groupId){const {group}=await requireGroup(s,payload.groupId);q.group_id=`eq.${group.id}`}if(payload.mineOnly||!p.canManage)q.requester_agent_user_id=`eq.${p.agentUserId}`;return {ok:true,tickets:arr(await restRequest({table:T.tickets,query:q})).map(publicTicket)}}
export async function replyToGroupTalkTicketCore(payload={}){const s=await staff(),p=profile(s),id=clean(payload.ticketId,160);let row=first(await restRequest({table:T.tickets,query:{select:"*",id:`eq.${id}`,limit:1}}));if(!row)row=first(await restRequest({table:T.tickets,query:{select:"*",ticket_number:`eq.${id}`,limit:1}}));if(!row)throw new Error("Ticket not found.");const {group}=await requireGroup(s,row.group_id||row.group_key);if(!p.canManage&&row.requester_agent_user_id!==p.agentUserId&&row.requester_sk_id!==p.skId)throw new Error("Not authorized for this ticket.");const body=clean(payload.body||payload.manifestText,6000);if(!body)throw new Error("Reply body is required.");const stamp=now();await restRequest({table:T.replies,method:"POST",body:{ticket_id:row.id,ticket_number:row.ticket_number,body,author_agent_user_id:p.agentUserId,author_sk_id:p.skId,author_name:p.displayName||p.fullName,reply_type:p.canManage?"operations":"staff",is_internal:true,payload:{manifestText:clean(payload.manifestText,10000),delivery:clean(payload.delivery,80),emailTo:clean(payload.emailTo,320)},created_at:stamp},prefer:"return=minimal"});const next=upper(payload.status)==="RESOLVED"?"resolved":row.status;const updated=first(await restRequest({table:T.tickets,method:"PATCH",query:{id:`eq.${row.id}`},body:{status:next,closed_at:next==="resolved"?stamp:row.closed_at,updated_at:stamp},prefer:"return=representation"}))||{...row,status:next,updated_at:stamp};const replies=arr(await restRequest({table:T.replies,query:{select:"*",ticket_id:`eq.${row.id}`,order:"created_at.asc",limit:500}}));const ticket=publicTicket(updated);await audit("TICKET_REPLY",s,{group,entityTable:T.tickets,entityId:row.id,ticketNo:row.ticket_number,payload:ticket});await broadcast(group,"ticket-updated",{ticket}).catch(()=>null);return {ok:true,ticket,messages:replies.map(publicReply)}}
export async function searchGroupTalkHistoryCore({query="",groupId="",limit=200}={}){const s=await staff();let group=null;if(groupId)group=(await requireGroup(s,groupId)).group;const q={select:"*",order:"created_at.desc",limit:Math.min(Math.max(Number(limit)||200,1),1000)};if(group)q.group_key=`eq.${group.group_key}`;const needle=lower(query),items=arr(await restRequest({table:T.history,query:q})).filter(r=>!needle||[r.event_type,r.actor_sk_id,r.actor_name,r.ticket_number,r.message,JSON.stringify(r.payload||{})].join(" ").toLowerCase().includes(needle)).map(r=>({id:r.id,eventType:r.event_type,groupKey:r.group_key,actorSkId:r.actor_sk_id,actorName:r.actor_name,ticketNumber:r.ticket_number,message:r.message,payload:obj(r.payload),createdAt:r.created_at}));return {ok:true,items}}
export async function adminSaveGroupCore(payload={}){const s=await ops(),p=profile(s),requested=clean(payload.groupId,160);let existing=requested?first(await restRequest({table:T.groups,query:{select:"*",id:`eq.${requested}`,limit:1}})):null;const name=clean(payload.title||payload.name,160)||existing?.name||"GroupTalk Group",key=existing?.group_key||`${slug(name)}-${rand(5)}`,old=obj(existing?.payload),body={group_key:key,name,description:clean(payload.description,1000)||existing?.description||"",channel_name:existing?.channel_name||`grouptalk-${key}`,livekit_room:clean(payload.livekitRoomName,220)||existing?.livekit_room||`grouptalk-${key}`,group_type:clean(payload.category||payload.groupType,80)||existing?.group_type||"Operations",visibility:payload.allowAllStaff===false?"members":"all_staff",status:payload.active===false?"inactive":"active",can_voice:payload.canStaffTalk!==false,can_chat:true,can_location:true,can_ticket:payload.canStaffCreateTickets!==false,sort_order:Number(payload.sortOrder||existing?.sort_order||0),payload:{...old,base:clean(payload.base,80)||old.base||"",defaultGroup:payload.defaultGroup===true,realtimeTopic:old.realtimeTopic||`grouptalk:${rand(20)}`},updated_at:now(),created_by_agent_user_id:p.agentUserId};const rows=await restRequest({table:T.groups,method:"POST",query:{on_conflict:"group_key"},body,prefer:"resolution=merge-duplicates,return=representation"});const saved=first(rows);await audit("ADMIN_SAVE_GROUP",s,{group:saved,entityTable:T.groups,entityId:saved?.id,payload:saved});return {ok:true,group:saved}}
async function resolveMember(key){const value=clean(key,320);if(!value)return null;for(const field of ["id","sk_id","corporate_email_address","email"]){const op=field==="id"?`eq.${value}`:`ilike.${value}`;const r=first(await restRequest({table:"agent_users",query:{select:"id,sk_id,first_name,last_name,preferred_name,display_name,corporate_email_address,email",[field]:op,limit:1}}));if(r)return r}return null}
export async function adminSetMembershipCore(payload={}){const s=await ops(),{group}=await requireGroup(s,payload.groupId),target=await resolveMember(payload.agentUserId||payload.memberKey||payload.skId||payload.email);if(!target)throw new Error("GROUPTALK_MEMBER_NOT_FOUND");const rows=await restRequest({table:T.members,method:"POST",query:{on_conflict:"group_key,agent_user_id"},body:{group_id:group.id,group_key:group.group_key,agent_user_id:target.id,sk_id:target.sk_id||null,display_name:target.display_name||target.preferred_name||[target.first_name,target.last_name].filter(Boolean).join(" "),email:target.corporate_email_address||target.email||null,role:clean(payload.role,80)||"member",membership_status:payload.active===false?"inactive":"active",can_talk:payload.canTalk!==false,can_listen:payload.canListen!==false,can_admin:payload.canAdmin===true,can_view_locations:payload.canViewLocations!==false,can_manage_tickets:payload.canManageTickets!==false,payload:{},created_by_agent_user_id:profile(s).agentUserId,updated_at:now()},prefer:"resolution=merge-duplicates,return=representation"});return {ok:true,membership:first(rows)}}
export async function getTicketCategoriesCore(){const s=await staff();return {ok:true,categories:(await ensureCategories(s)).filter(r=>r.is_active!==false).map(publicCategory)}}
export async function saveTicketCategoryCore(payload={}){const s=await ops(),c=obj(payload.category),label=clean(c.title||c.label||c.name,160);if(!label)throw new Error("Ticket category name is required.");const key=slug(c.categoryId||c.id||label),rows=await restRequest({table:T.categories,method:"POST",query:{on_conflict:"category_key"},body:{category_key:key,label,description:clean(c.description,1000),priority_default:lower(c.priorityDefault||"normal"),sla_minutes:Math.max(Number(c.slaMinutes||1440),1),is_active:c.active!==false,sort_order:Number(c.sort||c.sortOrder||100),payload:{},created_by_agent_user_id:profile(s).agentUserId,updated_at:now()},prefer:"resolution=merge-duplicates,return=representation"});return {ok:true,category:publicCategory(first(rows)||{}),categories:(await categoryRows()).map(publicCategory)}}
export async function deleteTicketCategoryCore(payload={}){await ops();const key=slug(payload.categoryId);await restRequest({table:T.categories,method:"PATCH",query:{category_key:`eq.${key}`},body:{is_active:false,updated_at:now()},prefer:"return=minimal"});return {ok:true,categories:(await categoryRows()).map(publicCategory)}}
