import wixLocationFrontend from "wix-location-frontend";
import { currentMember, authentication } from "wix-members-frontend";
import { getCustomerHeaderSession, subscribeCustomerNewsletter } from "backend/customerHeader.web";
import { getToursActivitiesBootstrap, searchToursActivities, getTourActivityDetail, createTourActivityBookingCart, searchNearbyToursActivities } from "backend/FINAL/toursActivitiesService.web";

const HTML_ID = "#toursActivitiesHtml";
const APP_SOURCE = "SKANDI_TOURS_ACTIVITIES";
const HEADER_SOURCE = "SKANDI_CUSTOMER_HEADER_EXPANDBAR";
const FOOTER_SOURCE = "SKANDI_CUSTOMER_FOOTER";
const PARENT_SOURCE = "SKANDI_WIX_PARENT";
let headerPromise = null;
let currentSettings = { language: "EN", currency: "USD" };

function asObject(value) { return value && typeof value === "object" && !Array.isArray(value) ? value : {}; }
function parseMessage(data) { if (typeof data === "string") { try { return JSON.parse(data); } catch (_) { return null; } } return asObject(data); }
function payloadOf(message) { return { ...asObject(message), ...asObject(message?.payload) }; }
function post(html, type, payload = {}, requestId = "") { html.postMessage({ source: PARENT_SOURCE, type, requestId, payload: { ...asObject(payload), requestId }, timestamp: new Date().toISOString() }); }
function closePanels(html) { post(html, "CLOSE_CUSTOMER_HEADER_PANELS", {}); }
function navigate(html, rawPath) { const path = String(rawPath || "").trim(); if (!path) return; if (!path.startsWith("/") && !/^https?:\/\//i.test(path) && !/^mailto:/i.test(path) && !/^tel:/i.test(path)) return; closePanels(html); wixLocationFrontend.to(path); }
function guestHeader() { return { loggedIn: false, displayName: "", points: 0, tierName: "", menu: [] }; }
async function memberSafe() { try { return await currentMember.getMember(); } catch (_) { return null; } }
async function sendHeaderState(html, refresh = false) { if (headerPromise && !refresh) return headerPromise; headerPromise = (async () => { try { const member = await memberSafe(); if (!member) { post(html, "CUSTOMER_HEADER_STATE", guestHeader()); return; } const session = await getCustomerHeaderSession(); post(html, "CUSTOMER_HEADER_STATE", { loggedIn: true, displayName: session?.displayName || member?.profile?.nickname || member?.loginEmail || "", points: Number(session?.points || session?.clubPoints || 0), tierName: session?.tierName || session?.tier || "", menu: Array.isArray(session?.menu) ? session.menu : [] }); } catch (error) { console.error("[Tours] Header state failed.", error); post(html, "CUSTOMER_HEADER_STATE", guestHeader()); } finally { headerPromise = null; } })(); return headerPromise; }
async function login(html) { closePanels(html); try { await authentication.promptLogin(); } catch (_) {} await sendHeaderState(html, true); }
async function logout(html) { closePanels(html); try { await Promise.resolve(authentication.logout()); } catch (_) {} post(html, "CUSTOMER_HEADER_STATE", guestHeader()); navigate(html, "/home"); }
function normalizeSettings(value = {}) { const language = ["EN","SV","NO","DA"].includes(String(value.language || "").toUpperCase()) ? String(value.language).toUpperCase() : "EN"; const currency = ["USD","SEK","NOK","DKK","EUR"].includes(String(value.currency || "").toUpperCase()) ? String(value.currency).toUpperCase() : "USD"; return { language, currency }; }
function queryState() { const query = wixLocationFrontend.query || {}; return { initialDestination: String(query.destination || ""), initialCategory: String(query.category || ""), initialActivity: String(query.activity || query.slug || "") }; }

async function handleHeader(html, message) { const p = payloadOf(message); if (message.type === "HEADER_READY") { await sendHeaderState(html); return true; } if (message.type === "HEADER_NAVIGATE") { navigate(html, p.path); return true; } if (message.type === "HEADER_SEARCH") { post(html, "TOURS_FOCUS_SEARCH", {}); return true; } if (message.type === "HEADER_LOGIN") { await login(html); return true; } if (message.type === "HEADER_LOGOUT") { await logout(html); return true; } if (message.type === "UPDATE_SETTINGS") { currentSettings = normalizeSettings(p); return true; } return false; }
async function handleFooter(html, message) { const p = payloadOf(message); if (message.type === "FOOTER_READY") { post(html, "CUSTOMER_FOOTER_STATE", { ready: true }); return true; } if (message.type === "FOOTER_NAVIGATE") { navigate(html, p.path); return true; } if (message.type === "FOOTER_STAFF_LOGIN") { navigate(html, "/riaintra"); return true; } if (message.type === "FOOTER_NEWSLETTER_SIGNUP") { const email = String(p.email || "").trim(); if (!email) { post(html, "FOOTER_NEWSLETTER_RESULT", { ok: false, message: "Please enter your email address." }); return true; } try { const result = await subscribeCustomerNewsletter({ email, source: p.source || "Tours & Activities Footer" }); post(html, "FOOTER_NEWSLETTER_RESULT", { ok: true, message: result?.status === "updated" ? "Your subscription is already active." : "Thank you for subscribing.", ...(result || {}) }); } catch (error) { post(html, "FOOTER_NEWSLETTER_RESULT", { ok: false, message: error?.message || "Newsletter signup failed." }); } return true; } return false; }
async function handleApp(html, message) { const p = payloadOf(message); const requestId = String(message.requestId || p.requestId || ""); if (message.type === "TOURS_READY") { currentSettings = normalizeSettings(p.settings || currentSettings); const initial = queryState(); const bootstrap = await getToursActivitiesBootstrap({ ...currentSettings, ...initial }); let initialActivity = null; if (initial.initialActivity) { try { const result = await getTourActivityDetail({ activityId: initial.initialActivity, ...currentSettings }); initialActivity = result?.activity || null; } catch (_) {} } post(html, "TOURS_BOOTSTRAP_RESULT", { ...(bootstrap || {}), initialActivity, initialDestination: initial.initialDestination, initialCategory: initial.initialCategory }, requestId); await sendHeaderState(html); return true; } if (message.type === "UPDATE_SETTINGS") { currentSettings = normalizeSettings(p); return true; } if (message.type === "TOURS_SEARCH") { const result = await searchToursActivities({ ...asObject(p.search), ...currentSettings }); post(html, "TOURS_SEARCH_RESULT", { ...(result || {}), items: Array.isArray(result?.items) ? result.items : [] }, requestId); return true; } if (message.type === "TOURS_ACTIVITY_OPEN") { const result = await getTourActivityDetail({ activityId: p.activityId, ...currentSettings }); post(html, "TOURS_ACTIVITY_RESULT", result || {}, requestId); return true; } if (message.type === "TOURS_NEARBY_SEARCH") { const result = await searchNearbyToursActivities({ latitude: Number(p.latitude), longitude: Number(p.longitude), ...currentSettings }); post(html, "TOURS_NEARBY_RESULT", result || {}, requestId); return true; } if (message.type === "TOURS_BOOK_ACTIVITY") { let result = await createTourActivityBookingCart({ activity: p.activity, selection: p.selection, ...currentSettings }); if (result?.requiresLogin) { await login(html); result = await createTourActivityBookingCart({ activity: p.activity, selection: p.selection, ...currentSettings }); } post(html, "TOURS_BOOK_RESULT", result || {}, requestId); return true; } if (message.type === "TOURS_FAVORITE") { if (!(await memberSafe())) await login(html); post(html, "TOURS_FAVORITE_RESULT", { ok: true, activityId: p.activityId }, requestId); return true; } if (message.type === "TOURS_NAVIGATE") { navigate(html, p.path); return true; } return false; }

$w.onReady(function () { let html; try { html = $w(HTML_ID); } catch (error) { console.error(`[Tours] Missing ${HTML_ID}.`, error); return; } html.onMessage(async event => { const message = parseMessage(event.data); if (!message?.source || !message?.type) return; try { if (message.source === APP_SOURCE) { await handleApp(html, message); return; } if (message.source === HEADER_SOURCE) { await handleHeader(html, message); return; } if (message.source === FOOTER_SOURCE) { await handleFooter(html, message); return; } } catch (error) { console.error(`[Tours] ${message.type} failed.`, error); post(html, "TOURS_ERROR", { message: error?.message || "The request could not be completed." }, message.requestId || ""); } }); });
