import { webMethod, Permissions } from 'wix-web-module';
import { isUuid, requireInternalAgent, text, writeInternalAudit } from '../RIA/internalAccess.js';
import { restRequest } from '../RIA/supabaseServer.js';

function now() { return new Date().toISOString(); }
function key() { return `INV-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`; }
function safeUrl(value) { const url = text(value, 2000); return /^https:\/\//i.test(url) ? url : ''; }
function mapItem(row = {}) { return { id: row.id || '', productId: row.product_id || row.id || '', productType: row.product_type || '', title: row.title || '', destination: row.destination || '', startDate: row.start_date || '', endDate: row.end_date || '', basePrice: Number(row.base_price || 0), livePrice: Number(row.live_price || 0), marginPct: Number(row.margin_pct || 0), currency: row.currency || 'SEK', availabilityStatus: row.availability_status || '', customerVisible: row.customer_visible === true, staffVisible: row.staff_visible === true, alteaVisible: row.altea_visible === true, bookingFlow: row.booking_flow || '', status: row.status || '', imageUrl: safeUrl(row.image_url), shortDescription: row.short_description || '', payload: row.payload || {} }; }
async function access() { return requireInternalAgent({ capability: 'manage' }); }
async function find(input = {}) { const id = text(input.id || input.productId || input.product_id, 160); if (!id) return null; const query = isUuid(id) ? { select: '*', id: `eq.${id}`, limit: 1 } : { select: '*', product_id: `eq.${id}`, limit: 1 }; const rows = await restRequest({ table: 'travel_products', query }); return rows?.[0] || null; }
async function audit(agent, action, target, after = {}) { await writeInternalAudit({ agent, action: `INVENTORY_${action}`, target, after }).catch(() => null); }

export const getInventorySchema = webMethod(Permissions.SiteMember, async () => { await access(); return { entity: 'travel_products', fields: ['productId', 'productType', 'title', 'destination', 'startDate', 'endDate', 'basePrice', 'livePrice', 'marginPct', 'currency', 'availabilityStatus', 'customerVisible', 'staffVisible', 'alteaVisible', 'bookingFlow', 'status', 'imageUrl', 'shortDescription'] }; });
export const listInventoryItems = webMethod(Permissions.SiteMember, async (input = {}) => { await access(); const rows = await restRequest({ table: 'travel_products', query: { select: '*', order: 'updated_at.desc', limit: Math.min(Math.max(Number(input.limit) || 1000, 1), 2000) } }); const query = text(input.query || input.search, 240).toLowerCase(); const status = text(input.status, 80).toUpperCase(); const items = (rows || []).map(mapItem).filter((item) => (!status || item.status.toUpperCase() === status) && (!query || `${item.productId} ${item.title} ${item.destination} ${item.productType}`.toLowerCase().includes(query))); return { ok: true, items }; });
export const getInventoryItem = webMethod(Permissions.SiteMember, async (input = {}) => { await access(); const row = await find(input); if (!row) throw new Error('INVENTORY_ITEM_NOT_FOUND'); return { ok: true, item: mapItem(row) }; });
async function saveItem(agent, input = {}) { const item = input.item || input; const existing = await find(item); const productId = text(item.productId || item.product_id || existing?.product_id, 160) || key(); const body = { product_id: productId, product_type: text(item.productType || item.product_type || existing?.product_type || 'PACKAGE', 100), title: text(item.title, 500) || 'Untitled inventory item', destination: text(item.destination, 240) || null, start_date: String(item.startDate || item.start_date || '').slice(0, 10) || null, end_date: String(item.endDate || item.end_date || '').slice(0, 10) || null, base_price: Number(item.basePrice ?? item.base_price) || 0, live_price: Number(item.livePrice ?? item.live_price) || 0, margin_pct: Number(item.marginPct ?? item.margin_pct) || 0, currency: text(item.currency || 'SEK', 3), availability_status: text(item.availabilityStatus || item.availability_status || 'AVAILABLE', 80), customer_visible: item.customerVisible === true, staff_visible: item.staffVisible !== false, altea_visible: item.alteaVisible !== false, booking_flow: text(item.bookingFlow || item.booking_flow, 120) || null, status: text(item.status || existing?.status || 'DRAFT', 80).toUpperCase(), image_url: safeUrl(item.imageUrl || item.image_url) || null, short_description: text(item.shortDescription || item.short_description, 4000) || null, payload: { ...(existing?.payload || {}), ...item, productId }, created_by_agent_user_id: existing?.created_by_agent_user_id || agent.id, updated_at: now() }; const rows = existing ? await restRequest({ table: 'travel_products', method: 'PATCH', query: { id: `eq.${existing.id}` }, body }) : await restRequest({ table: 'travel_products', method: 'POST', body: { ...body, created_at: now() } }); const saved = rows?.[0] || existing; await audit(agent, 'ITEM_SAVED', saved?.id, { productId }); return { ok: true, item: mapItem(saved || {}) }; }
export const saveInventoryItem = webMethod(Permissions.SiteMember, async (input = {}) => saveItem((await access()).agent, input));
export const duplicateInventoryItem = webMethod(Permissions.SiteMember, async (input = {}) => { const { agent } = await access(); const source = await find(input); if (!source) throw new Error('INVENTORY_ITEM_NOT_FOUND'); const sourceItem = mapItem(source); const copy = await saveItem(agent, { item: { ...sourceItem, id: '', productId: key(), title: `${sourceItem.title} (Copy)`, status: 'DRAFT', customerVisible: false } }); await audit(agent, 'ITEM_DUPLICATED', source.id, { copyId: copy.item?.id }); return copy; });
export const deleteInventoryItem = webMethod(Permissions.SiteMember, async (input = {}) => { const { agent } = await access(); const row = await find(input); if (!row) throw new Error('INVENTORY_ITEM_NOT_FOUND'); const rows = await restRequest({ table: 'travel_products', method: 'PATCH', query: { id: `eq.${row.id}` }, body: { status: 'ARCHIVED', customer_visible: false, updated_at: now() } }); const saved = rows?.[0] || row; await audit(agent, 'ITEM_ARCHIVED', saved.id); return { ok: true, item: mapItem(saved) }; });
