// backend/RIA/alteaEnterpriseV912.web.js
// SKANDI ALTEA Reservations V9.12.1 enterprise compatibility + operations service.
import { webMethod, Permissions } from "wix-web-module";
import { getStaffPortalSession } from "backend/RIA/staffPortalAuth.web";
import { restRequest } from "backend/RIA/supabaseServer.js";
import { checkExternalTravelRequirements } from "backend/RIA/travelRequirementsProvider.web";

const clean=(v,n=12000)=>String(v??"").trim().slice(0,n);
const upper=(v,n=120)=>clean(v,n).toUpperCase();
const arr=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
const isUuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(clean(v,80));
const qeq=v=>`eq.${clean(v,300)}`;
async function staff(){const s=await getStaffPortalSession();if(!s||s.ok===false||s.authorized===false)throw new Error("AUTH_REQUIRED");return s}
function actor(s){return isUuid(s?.profile?.id)?s.profile.id:null}
async function select(table,query={}){return arr(await restRequest({table,method:"GET",query,prefer:""}))}
async function patch(table,query,body){return arr(await restRequest({table,method:"PATCH",query,body,prefer:"return=representation"}))}
async function insert(table,body){return arr(await restRequest({table,method:"POST",body,prefer:"return=representation"}))}
function mergePayload(row,extra){return{...obj(row?.payload),...obj(extra)}}
async function bookingRow(id){if(!isUuid(id))return null;return (await select("altea_bookings",{select:"*",id:qeq(id),limit:"1"}))[0]||null}
async function passengerRow(id){if(!isUuid(id))return null;return (await select("altea_passengers",{select:"*",id:qeq(id),limit:"1"}))[0]||null}
async function componentRow(id){if(!isUuid(id))return null;return (await select("altea_booking_components",{select:"*",id:qeq(id),limit:"1"}))[0]||null}
async function history(bookingId,eventType,payload={},s=null){const b=await bookingRow(bookingId);return insert("altea_pnr_history",{booking_id:isUuid(bookingId)?bookingId:null,pnr_locator:b?.pnr_locator||null,event_type:upper(eventType,100),payload:obj(payload),created_by_agent_user_id:actor(s),supplier:"SKANDI"})}
function bookingPatch(input={}){
  const p=obj(input);const db={};const payload={};
  if(p.bookingType!==undefined)db.booking_type=upper(p.bookingType,80);
  if(p.productType!==undefined)db.product_type=upper(p.productType,80);
  if(p.status!==undefined)db.status=clean(p.status,80).toLowerCase();
  if(p.paymentStatus!==undefined)db.payment_status=clean(p.paymentStatus,80).toLowerCase();
  if(p.fulfillmentStatus!==undefined)db.fulfillment_status=clean(p.fulfillmentStatus,80).toLowerCase();
  if(p.customerName!==undefined)db.customer_name=clean(p.customerName,300);
  if(p.customerEmail!==undefined)db.customer_email=clean(p.customerEmail,400).toLowerCase();
  if(p.origin!==undefined)db.origin=upper(p.origin,12);
  if(p.destination!==undefined)db.destination=upper(p.destination,12);
  if(p.startDate!==undefined||p.departureDate!==undefined)db.departure_date=clean(p.startDate||p.departureDate,20)||null;
  if(p.endDate!==undefined||p.returnDate!==undefined)db.return_date=clean(p.endDate||p.returnDate,20)||null;
  if(p.currency!==undefined)db.currency=upper(p.currency,3);
  if(p.totalAmount!==undefined)db.total_amount=Number(p.totalAmount||0);
  for(const key of ["tripTitle","transferControl","packageStatus","dcsAuthority","operatingControl","isCharter","notes"])if(p[key]!==undefined)payload[key]=p[key];
  return{db,payload};
}

export const updateAlteaBookingEnterprise=webMethod(Permissions.SiteMember,async(input={})=>{
  const s=await staff();const id=clean(input.bookingId,80);if(!isUuid(id))throw new Error("BOOKING_REQUIRED");const before=await bookingRow(id);if(!before)throw new Error("BOOKING_NOT_FOUND");const mapped=bookingPatch(input.patch||{});const body={...mapped.db};if(Object.keys(mapped.payload).length)body.payload=mergePayload(before,mapped.payload);const updated=(await patch("altea_bookings",{id:qeq(id)},body))[0]||before;await history(id,"BOOKING_UPDATED",{before:{booking_type:before.booking_type,status:before.status},after:{booking_type:updated.booking_type,status:updated.status},changed:Object.keys({...mapped.db,...mapped.payload})},s);return{ok:true,booking:updated};
});

function clubView(r={}){const p=obj(r.payload);return{id:r.id,memberId:r.member_id,memberNumber:clean(p.memberNumber||p.member_number||r.club_id||r.member_id,100),clubId:r.club_id,name:clean(p.name||p.displayName||p.customerName||p.fullName||r.member_id,300),email:clean(p.email||p.customerEmail,400),tier:upper(p.tier||p.tierName||"MEMBER",80),pointsBalance:Number(p.pointsBalance??p.points??0)||0,status:r.status||"Active",dateOfBirth:r.date_of_birth||null,nationalityId:r.nationality_id||null,homeAirportId:r.home_airport_id||null,payload:p}}
export const searchSkandiClubMembers=webMethod(Permissions.SiteMember,async(input={})=>{await staff();const q=clean(input.query,200).toLowerCase();const rows=await select("club_profiles",{select:"*",limit:"500",order:"updated_at.desc"});const members=rows.map(clubView).filter(x=>!q||`${x.memberNumber} ${x.memberId} ${x.name} ${x.email} ${JSON.stringify(x.payload)}`.toLowerCase().includes(q)).slice(0,100);return{ok:true,members}});
export const linkSkandiClubMember=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();if(!isUuid(input.passengerId)||!isUuid(input.memberId))throw new Error("CLUB_LINK_INPUT_INVALID");const [p,mrows]=await Promise.all([passengerRow(input.passengerId),select("club_profiles",{select:"*",id:qeq(input.memberId),limit:"1"})]);const member=mrows[0];if(!p||!member)throw new Error("CLUB_MEMBER_OR_PASSENGER_NOT_FOUND");const mv=clubView(member);const payload=mergePayload(p,{clubProfile:mv,clubProfileId:member.id});await patch("altea_passengers",{id:qeq(p.id)},{payload});if(isUuid(input.bookingId))await patch("altea_bookings",{id:qeq(input.bookingId)},{customer_member_id:member.member_id});await history(input.bookingId||p.booking_id,"SKANDI_CLUB_LINKED",{passengerId:p.id,memberId:member.id,memberNumber:mv.memberNumber},s);return{ok:true,passengerId:p.id,member:mv,message:"SKANDI Club member linked to passenger."}});
export const adjustSkandiClubPoints=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();if(!isUuid(input.memberId))throw new Error("CLUB_MEMBER_REQUIRED");const rows=await select("club_profiles",{select:"*",id:qeq(input.memberId),limit:"1"});const row=rows[0];if(!row)throw new Error("CLUB_MEMBER_NOT_FOUND");const delta=Math.trunc(Number(input.delta||0));if(!delta)throw new Error("POINTS_DELTA_REQUIRED");const reason=clean(input.reason,1000);if(!reason)throw new Error("POINTS_REASON_REQUIRED");const p=obj(row.payload);const next=Math.max(0,(Number(p.pointsBalance??p.points??0)||0)+delta);p.pointsBalance=next;p.points=next;p.lastPointsAdjustment={delta,reason,at:new Date().toISOString(),actorId:actor(s)};const updated=(await patch("club_profiles",{id:qeq(row.id)},{payload:p,updated_at:new Date().toISOString()}))[0]||{...row,payload:p};await history(input.bookingId,"SKANDI_CLUB_POINTS_ADJUSTED",{memberId:row.id,passengerId:input.passengerId||null,delta,reason,balance:next},s);return{ok:true,passengerId:input.passengerId||"",member:clubView(updated),message:`SKANDI Club points updated by ${delta}.`}});

function normalizeRequirement(r={}){return{id:r.id,title:r.title||"Travel requirement",category:r.category||"GUIDANCE",body:r.body||"",payload:obj(r.payload)}}
export const checkAlteaTravelRequirements=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();const b=await bookingRow(input.bookingId);const p=await passengerRow(input.passengerId);const traveler={id:p?.id||input.passengerId,nationality:upper(input.nationality||p?.nationality,3),residenceCountry:upper(input.residenceCountry,3),dateOfBirth:input.dateOfBirth||p?.date_of_birth||null,documentType:upper(input.documentType||"PASSPORT",40),documentIssuingCountry:upper(input.documentIssuingCountry,3),documentExpiry:input.documentExpiry||null};const cart={searchContext:{origin:upper(input.origin||b?.origin,12),destination:upper(input.destination||b?.destination,12),departureDate:b?.departure_date||"",returnDate:b?.return_date||"",transitPoints:arr(input.transitPoints)}};let external={connected:false,status:"NEEDS_PROVIDER",provider:"NONE"};try{external=await checkExternalTravelRequirements({cart,travelers:[traveler]})}catch(_){}const local=(await select("travel_requirements",{select:"*",active:"eq.true",order:"sort_order.asc",limit:"300"})).map(normalizeRequirement);const hayNeed=[traveler.nationality,cart.searchContext.origin,cart.searchContext.destination,...arr(cart.searchContext.transitPoints)].filter(Boolean).map(lower=>String(lower).toLowerCase());const matches=local.filter(r=>{const h=`${r.title} ${r.category} ${r.body} ${JSON.stringify(r.payload)}`.toLowerCase();return !hayNeed.length||hayNeed.some(k=>h.includes(k))});const decision=external.connected?{status:external.status,summary:external.summary,provider:external.provider,result:external.decision||external.raw||null,notices:external.notices||[]}:{status:matches.length?"SKANDI_GUIDANCE_MATCHED":"GUIDANCE_ONLY",summary:matches.length?"SKANDI guidance matched this passenger/route. This is not a live Timatic/IATA boarding decision.":"No route-specific SKANDI requirement record matched. Confirm official entry requirements before travel.",provider:"SKANDI_GUIDANCE",guidance:matches.slice(0,30),notices:["No live Timatic/IATA decision is represented unless an authorized external provider is connected."]};if(p){const payload=mergePayload(p,{travelRequirementStatus:decision.status,travelRequirementDecision:decision,travelRequirementCheckedAt:new Date().toISOString()});await patch("altea_passengers",{id:qeq(p.id)},{payload});}await history(input.bookingId||p?.booking_id,"TRAVEL_REQUIREMENTS_CHECKED",{passengerId:p?.id||input.passengerId,provider:decision.provider,status:decision.status},s);return{ok:true,provider:decision.provider,decision};});

function docNumber(type){return `SK-${upper(type,24).replace(/[^A-Z0-9]/g,"").slice(0,12)}-${Date.now().toString().slice(-10)}`}
function requestedDocNumber(value,type){const v=upper(value,120).replace(/[^A-Z0-9-]/g,"").slice(0,80);return v||docNumber(type)}
function isSkandiDcsBooking(b={}){const p=obj(b.payload);const kind=upper(b.booking_type||b.product_type,80);return upper(b.supplier,40)==="SKANDI"||upper(p.dcsAuthority,40)==="SKANDI"||upper(p.operatingControl,40)==="SKANDI"||p.isCharter===true||kind.includes("CHARTER")}
async function hasTransferAuthority(bookingId,componentId=""){const q={select:"id,booking_id,component_type,status",booking_id:qeq(bookingId),limit:"500"};const rows=await select("altea_booking_components",q);return rows.some(c=>(!componentId||c.id===componentId)&&upper(c.component_type,80).includes("TRANSFER")&&!['REMOVED','CANCELLED'].includes(upper(c.status,80)))}
function docHtml(type,b,p=null,authority="SKANDI_BOOKING"){const ref=clean(b?.booking_reference||b?.pnr_locator||b?.id,120);const name=clean(p?.display_name||`${p?.first_name||""} ${p?.last_name||""}`.trim()||b?.customer_name||"Customer",300);const notice=authority==="SKANDI_CHARTER_DCS"?"This document is valid only for the SKANDI-controlled charter departure recorded in ALTEA. It is not an airline-issued document for supplier-controlled flights.":authority==="SKANDI_TRANSFER"?"This is a SKANDI transfer operations document. It is not an airline boarding pass, airline ticket, EMD, or airline baggage tag.":"This is a SKANDI-controlled booking document. Airline-issued tickets, EMDs, boarding passes and airline baggage tags remain supplier-controlled.";return `<!doctype html><html><body style="font-family:Arial,sans-serif;padding:32px;color:#17212b"><h1 style="color:#005eb8">SKANDI TRAVELS</h1><h2>${clean(type,120)}</h2><p><b>Booking reference:</b> ${ref}</p><p><b>Passenger/Customer:</b> ${name}</p><p>${notice}</p></body></html>`}
async function generateDocumentCore(input={},s=null){const id=clean(input.bookingId,80);if(!isUuid(id))throw new Error("BOOKING_REQUIRED");const b=await bookingRow(id);if(!b)throw new Error("BOOKING_NOT_FOUND");const p=isUuid(input.passengerId)?await passengerRow(input.passengerId):null;const type=upper(input.documentType||"BOOKING_CONFIRMATION",80);if(["ETKT","E_TICKET","EMD","AIRLINE_BOARDING_PASS","AIRLINE_BAG_TAG"].includes(type))throw new Error("SUPPLIER_DOCUMENT_AUTHORITY_REQUIRED");let authority="SKANDI_BOOKING";if(["BOARDING_PASS","BAG_TAG"].includes(type)){if(!isSkandiDcsBooking(b))throw new Error("SKANDI_DCS_AUTHORITY_REQUIRED");authority="SKANDI_CHARTER_DCS"}if(type.startsWith("TRANSFER_")){const componentId=clean(input.componentId||input.departureId,80);if(!(await hasTransferAuthority(id,componentId)))throw new Error("SKANDI_TRANSFER_AUTHORITY_REQUIRED");authority="SKANDI_TRANSFER"}const number=requestedDocNumber(input.documentNumber,type);const payload={source:"ALTEA_V9_12_1",bookingReference:b.booking_reference,provider:"SKANDI",authority,componentId:input.componentId||input.departureId||null};const rows=await insert("altea_documents",{booking_id:id,passenger_id:p?.id||null,document_type:type,document_number:number,status:"active",html_snapshot:docHtml(type,b,p,authority),issued_at:new Date().toISOString(),issued_by_agent_user_id:actor(s),payload});const d=rows[0];await insert("altea_booking_documents",{booking_id:id,passenger_id:p?.id||null,provider:"SKANDI",provider_document_id:d?.id||number,document_type:type,document_number:number,status:"ACTIVE",payload:{alteaDocumentId:d?.id||null,authority,componentId:input.componentId||input.departureId||null}});await history(id,"DOCUMENT_GENERATED",{documentId:d?.id,documentType:type,documentNumber:number,authority},s);return{ok:true,document:{id:d?.id,documentType:type,documentNumber:number,status:"ACTIVE",provider:"SKANDI",authority,htmlSnapshot:d?.html_snapshot},message:"SKANDI document generated."}}
export const generateAlteaBookingDocument=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();return generateDocumentCore(input,s)});
export const requestAlteaDocumentDelivery=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();const id=clean(input.bookingId,80);if(!isUuid(id))throw new Error("BOOKING_REQUIRED");await history(id,"DOCUMENT_DELIVERY_REQUESTED",{documentType:upper(input.documentType,80),documentId:input.documentId||null,componentId:input.componentId||null,recipient:clean(input.recipient,400)},s);return{ok:true,status:"QUEUED",message:"Document delivery request recorded for the SKANDI mail/document workflow."}});

export const updateAlteaDcsPassenger=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();const p=await passengerRow(input.passengerId);if(!p)throw new Error("PASSENGER_NOT_FOUND");const change=obj(input.patch);const body={payload:mergePayload(p,change)};if(change.apisStatus!==undefined)body.apis_status=clean(change.apisStatus,80);if(change.documentStatus!==undefined)body.document_status=clean(change.documentStatus,80);if(change.checkinStatus!==undefined)body.checkin_status=clean(change.checkinStatus,80);if(change.seatNumber!==undefined)body.seat_number=clean(change.seatNumber,20);if(change.sequenceNumber!==undefined)body.sequence_number=clean(change.sequenceNumber,30);const updated=(await patch("altea_passengers",{id:qeq(p.id)},body))[0]||p;await history(input.bookingId||p.booking_id,"DCS_PASSENGER_UPDATED",{passengerId:p.id,patch:change},s);return{ok:true,passenger:updated}});

function transferDeparture(component,booking,passengers){const p=obj(component.payload);const state=obj(p.transferDcsState);const service=clean(p.serviceNumber||p.transferNumber||component.supplier_reference||`TRF-${String(component.id).slice(0,8).toUpperCase()}`,120);return{id:String(component.id),componentId:component.id,bookingId:component.booking_id,serviceNumber:service,origin:clean(p.pickupLocation||p.origin||booking?.origin||"Airport / pickup",500),destination:clean(p.dropoffLocation||p.destination||p.hotelName||booking?.destination||"Hotel / destination",500),date:clean(p.serviceDate||p.startDate||booking?.departure_date,20),scheduled:clean(p.serviceTime||p.pickupTime||"—",30),estimated:clean(state.estimated||p.estimatedDeparture||p.serviceTime||p.pickupTime||"—",30),bay:clean(state.bay||p.bay||p.meetingPoint||"—",300),vehicle:clean(state.vehicle||p.vehicleName||p.vehicleType||"Coach",300),vehicleRegistration:clean(state.vehicleRegistration||p.vehicleRegistration,100),capacity:Number(state.capacity||p.capacity||p.vehicleCapacity||50)||50,booked:passengers.length,driver:clean(state.driver||p.driverName||"—",300),guide:clean(state.guide||p.guideName||p.hostName||"—",300),terminal:clean(p.terminal||p.airportTerminal,80),associatedFlight:clean(p.associatedFlight||p.flightNumber,80),status:upper(state.status||p.transferStatus||p.operationalStatus||"OPEN",80),raw:{...component,payload:p,passengers:passengers.map(x=>({id:x.id,passengerId:x.id,passengerRef:x.passenger_ref,firstName:x.first_name,lastName:x.last_name,displayName:x.display_name,nationality:x.nationality,bookingReference:booking?.booking_reference,pnrLocator:booking?.pnr_locator,payload:x.payload,transferDcs:obj(x.payload?.transferDcs)}))}}}
export const getTransferDcsBootstrap=webMethod(Permissions.SiteMember,async(input={})=>{await staff();const rows=await select("altea_booking_components",{select:"*",order:"created_at.desc",limit:"1000"});let transfers=rows.filter(c=>upper(c.component_type,80).includes("TRANSFER")&&!['REMOVED','CANCELLED'].includes(upper(c.status,80)));if(isUuid(input.bookingId))transfers=transfers.filter(c=>c.booking_id===input.bookingId);const bids=[...new Set(transfers.map(c=>c.booking_id).filter(Boolean))];if(!bids.length)return{ok:true,departures:[],persistenceAvailable:true};const [bookings,pax]=await Promise.all([select("altea_bookings",{select:"*",id:`in.(${bids.join(',')})`,limit:"1000"}),select("altea_passengers",{select:"*",booking_id:`in.(${bids.join(',')})`,limit:"5000"})]);const bm=new Map(bookings.map(b=>[b.id,b]));return{ok:true,departures:transfers.map(c=>transferDeparture(c,bm.get(c.booking_id),pax.filter(x=>x.booking_id===c.booking_id))),persistenceAvailable:true}});
export const updateTransferDcsPassenger=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();const p=await passengerRow(input.passengerId);if(!p)throw new Error("PASSENGER_NOT_FOUND");const dep=clean(input.departureId||input.componentId,100);const payload=obj(p.payload);const td=obj(payload.transferDcs);td[dep]={...obj(td[dep]),...obj(input.patch),updatedAt:new Date().toISOString()};payload.transferDcs=td;if(input.patch?.bags!==undefined)payload.baggageCount=Number(input.patch.bags||0);if(input.patch?.weight!==undefined)payload.baggageWeight=Number(input.patch.weight||0);await patch("altea_passengers",{id:qeq(p.id)},{payload});await history(input.bookingId||p.booking_id,"TRANSFER_DCS_PASSENGER_UPDATED",{departureId:dep,passengerId:p.id,patch:obj(input.patch)},s);return{ok:true,passengerId:p.id}});
export const updateTransferDcsDeparture=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();const c=await componentRow(input.componentId||input.departureId);if(!c)throw new Error("TRANSFER_COMPONENT_NOT_FOUND");const payload=obj(c.payload);payload.transferDcsState={...obj(payload.transferDcsState),...obj(input.patch),updatedAt:new Date().toISOString()};await patch("altea_booking_components",{id:qeq(c.id)},{payload});await history(input.bookingId||c.booking_id,"TRANSFER_DCS_DEPARTURE_UPDATED",{componentId:c.id,patch:obj(input.patch)},s);return{ok:true,componentId:c.id}});
export const recordTransferDcsDocument=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();return generateDocumentCore({bookingId:input.bookingId,passengerId:input.passengerId,componentId:input.componentId||input.departureId,departureId:input.departureId,documentType:input.documentType||"TRANSFER_DOCUMENT",documentNumber:input.documentNumber},s)});
export const sendAlteaManifest=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();const b=await bookingRow(input.bookingId);if(!b)throw new Error("BOOKING_NOT_FOUND");const passengers=await select("altea_passengers",{select:"*",booking_id:qeq(b.id),order:"created_at.asc"});const components=await select("altea_booking_components",{select:"*",booking_id:qeq(b.id),order:"created_at.asc"});const number=`MAN-${Date.now().toString().slice(-10)}`;const rows=await insert("operational_manifests",{title:`${upper(input.manifestType||"PASSENGERS",80)} · ${b.booking_reference||b.pnr_locator||b.id}`,status:"READY",manifest_number:number,route:[b.origin,b.destination].filter(Boolean).join("-")||null,departure:b.departure_date?`${b.departure_date}T00:00:00Z`:null,payload:{bookingId:b.id,bookingReference:b.booking_reference,pnrLocator:b.pnr_locator,manifestType:upper(input.manifestType||"PASSENGERS",80),passengers,components,generatedAt:new Date().toISOString()}});await history(b.id,"MANIFEST_GENERATED",{manifestId:rows[0]?.id,manifestNumber:number,manifestType:input.manifestType},s);return{ok:true,manifest:rows[0],message:"Operational manifest generated and recorded."}});
