// backend/RIA/inventoryReservationsV9.web.js
// SKANDI Inventory Control -> ALTEA Reservations atomic sell/release bridge V9.12
import { webMethod, Permissions } from "wix-web-module";
import { getStaffPortalSession } from "backend/RIA/staffPortalAuth.web";
import { restRequest, rpcRequest } from "backend/RIA/supabaseServer.js";
const clean=(v,n=6000)=>String(v??"").trim().slice(0,n),upper=v=>clean(v,120).toUpperCase(),arr=v=>Array.isArray(v)?v:[];
const isUuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(clean(v,80));
async function staff(){const s=await getStaffPortalSession();if(!s||s.ok===false||s.authorized===false)throw new Error("AUTH_REQUIRED");return s}
async function select(table,query={}){return arr(await restRequest({table,method:"GET",query,prefer:""}))}
function actor(s){return isUuid(s?.profile?.id)?s.profile.id:null}
export const searchReservationInventory=webMethod(Permissions.SiteMember,async(input={})=>{await staff();const q=clean(input.query,200).toLowerCase(),type=upper(input.entityType||input.type),date=clean(input.serviceDate,20);const allowed=new Set(["HOTEL","TRANSFER","GUIDED_TOUR","ACTIVITY","PARTNER_TICKET","PACKAGE","ANCILLARY","CAR_RENTAL"]);const types=type&&allowed.has(type)?new Set([type]):allowed;const rows=await select("inventory_master_entities",{select:"id,public_id,entity_type,code,name,slug,status,active,altea_visible,details,commercial,operations,source,source_reference",active:"eq.true",altea_visible:"eq.true",limit:"1000",order:"sort_priority.asc"});const items=rows.filter(r=>types.has(upper(r.entity_type))&&["PUBLISHED","REVIEW"].includes(upper(r.status))&&(!q||`${r.code} ${r.name} ${JSON.stringify(r.details||{})}`.toLowerCase().includes(q))).slice(0,200);const ids=items.map(x=>x.id);let dated=[];if(ids.length){const query={select:"*",entity_id:`in.(${ids.join(',')})`,order:"service_date.asc,start_time.asc",limit:"1000"};if(date)query.service_date=`eq.${date}`;dated=await select("inventory_dated_inventory",query)}return{ok:true,items:items.map(r=>{const d=r.details||{},c=r.commercial||{},o=r.operations||{};return{...r,publicId:r.public_id,entityType:r.entity_type,entityTypeCode:r.entity_type,city:d.city||o.city||"",destination:d.destination||o.destination||"",category:d.category||"",publicPrice:Number(c.publicPrice??c.price??0)||0,currency:String(c.currency||"USD").toUpperCase(),dated:dated.filter(x=>x.entity_id===r.id).map(x=>({...x,datedInventoryId:x.id,serviceDate:x.service_date,variantCode:x.variant_code,variantName:x.variant_name,publicPrice:Number(x.public_price??x.adult_price??0)||0,currency:String(x.currency||c.currency||"USD").toUpperCase(),available:Number(x.available??0)||0,stopSale:Boolean(x.stop_sale),blackout:Boolean(x.blackout)}))}}),serviceDate:date}});
export const addReservationInventoryComponent=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();if(!isUuid(input.bookingId)||!isUuid(input.entityId))throw new Error("INVENTORY_COMPONENT_INPUT_INVALID");const datedRows=await select("inventory_dated_inventory",{select:"id,status,stop_sale,blackout,available",entity_id:`eq.${input.entityId}`,limit:"250"});if(datedRows.length&&!isUuid(input.datedInventoryId))throw new Error("DATED_INVENTORY_SELECTION_REQUIRED");const r=await rpcRequest({functionName:"inventory_altea_add_component_v9",body:{p_booking_id:input.bookingId,p_entity_id:input.entityId,p_dated_inventory_id:isUuid(input.datedInventoryId)?input.datedInventoryId:null,p_quantity:Math.max(1,Math.min(99,Number(input.quantity||1))),p_agent_user_id:actor(s)}});return{ok:true,component:Array.isArray(r)?r[0]:r}});
export const releaseReservationInventoryComponent=webMethod(Permissions.SiteMember,async(input={})=>{const s=await staff();if(!isUuid(input.componentId))throw new Error("BOOKING_COMPONENT_NOT_FOUND");const rows=await select("altea_booking_components",{select:"id,supplier,source_entity_id,payload",id:`eq.${input.componentId}`,limit:"1"});const c=rows[0];if(!c)throw new Error("BOOKING_COMPONENT_NOT_FOUND");if(upper(c.supplier)!=="SKANDI"&&!c.source_entity_id)throw new Error("SUPPLIER_COMPONENT_MUST_BE_SERVICED_EXTERNALLY");const r=await rpcRequest({functionName:"inventory_altea_release_component_v9",body:{p_component_id:input.componentId,p_agent_user_id:actor(s)}});return{ok:true,component:Array.isArray(r)?r[0]:r}});
export const getReservationInventoryStatus=webMethod(Permissions.SiteMember,async(input={})=>{await staff();if(!isUuid(input.bookingId))throw new Error("BOOKING_REQUIRED");const [booking,components]=await Promise.all([select("altea_bookings",{select:"*",id:`eq.${input.bookingId}`,limit:"1"}),select("altea_booking_components",{select:"*",booking_id:`eq.${input.bookingId}`,order:"created_at.asc"})]);return{ok:true,booking:booking[0]||null,components}});
