import { webMethod, Permissions } from "wix-web-module";
import { secrets } from "wix-secrets-backend.v2";
import { elevate } from "wix-auth";
import { fetch } from "wix-fetch";
import { getStaffPortalSession } from "backend/RIA/staffPortalAuth.web";

const TABLES={master:"inventory_master_entities",localized:"inventory_localized_content",media:"inventory_media_assets",relations:"inventory_entity_relations",dated:"inventory_dated_inventory",audit:"master_inventory_audit",airports:"travel_info_airports",airlines:"travel_info_airlines"};
const REFERENCE_TYPES=new Set(["AIRPORT","AIRLINE"]);
const ENTITY_TYPES=new Set(["DESTINATION","AIRPORT","AIRLINE","SUPPLIER","HOTEL","GUIDED_TOUR","ACTIVITY","PARTNER_TICKET","TRANSFER","CAR_RENTAL","PACKAGE","ANCILLARY"]);
const MASTER_STATUSES=new Set(["DRAFT","REVIEW","PUBLISHED","HIDDEN","SUSPENDED","ARCHIVED"]);
const DATED_STATUSES=new Set(["OPEN","CLOSED","STOP_SALE","BLACKOUT","SOLD_OUT"]);
const LANGUAGES=["EN","SV","NO","DA","FI"];

const clean=(v,m=1000)=>String(v??"").trim().slice(0,m);
const upper=(v,m=1000)=>clean(v,m).toUpperCase();
function bool(v,f=false){if([true,"true","YES",1,"1"].includes(v))return true;if([false,"false","NO",0,"0"].includes(v))return false;return f}
function num(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
const int=(v,f=0)=>Math.trunc(num(v,f));
function arr(v){if(Array.isArray(v))return v;if(v==null||v==="")return[];return String(v).split(/\n|,/).map(x=>x.trim()).filter(Boolean)}
const object=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
const slugify=v=>clean(v,240).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,160);
const safeDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(clean(v,20))?clean(v,20):null;
const safeTime=v=>/^\d{2}:\d{2}(:\d{2})?$/.test(clean(v,12))?clean(v,12):null;
const eq=(f,v)=>`${f}=eq.${encodeURIComponent(String(v))}`;

const elevatedGetSecretValue=elevate(secrets.getSecretValue);
let configurationPromise=null;
function secretString(r){return typeof r==="string"?r.trim():String(r?.value??r?.secretValue??r?.secret?.value??"").trim()}
async function readSecret(name){const r=await elevatedGetSecretValue(name);const v=secretString(r);if(!v)throw new Error(`WIX_SECRET_EMPTY_${name}`);return v}
async function cfg(){
  if(configurationPromise)return configurationPromise;
  configurationPromise=(async()=>{
    const url=(await readSecret("SUPABASE_URL")).replace(/\/+$/,"");
    let key="";try{key=await readSecret("SUPABASE_SECRET_KEY")}catch(_e){key=await readSecret("SUPABASE_SERVICE_ROLE_KEY")}
    if(!/^https:\/\/[^/]+\.supabase\.co$/i.test(url))throw new Error("SUPABASE_URL_INVALID");
    if(!key)throw new Error("SUPABASE_SERVER_KEY_MISSING");
    return{url,key,keyType:key.startsWith("sb_secret_")?"modern-secret":key.startsWith("eyJ")?"legacy-jwt":"api-key"};
  })();
  try{return await configurationPromise}catch(error){configurationPromise=null;throw error}
}
async function sb(path,{method="GET",body,headers={}}={}){
  const c=await cfg();
  const r=await fetch(`${c.url}/rest/v1/${path}`,{method,headers:{apikey:c.key,...(c.keyType==="legacy-jwt"?{Authorization:`Bearer ${c.key}`} : {}),"Content-Type":"application/json",...(method==="POST"||method==="PATCH"?{Prefer:"return=representation"}:{}),...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})});
  const t=await r.text();let d=null;if(t){try{d=JSON.parse(t)}catch(_e){d=t}}
  if(!r.ok){const e=new Error(d?.message||d?.error||`${r.status} ${r.statusText}`);e.code=d?.code||"";throw e}return d;
}
function profileOf(s={}){
  const p=s.profile||s.staff||s.user||s.data?.profile||{};
  return{
    wixProfileId:p.id||"",
    skId:upper(p.skId||p.sk_id||p.employeeId||p.employee_id,40),
    name:clean(p.name||p.fullName||p.title||p.displayName||p.display_name||p.email,160),
    email:clean(p.email,200).toLowerCase()
  };
}
async function resolveSupabaseActor(profile){
  let rows=[];
  if(profile.skId){
    rows=await sb(`agent_users?select=id,sk_id,email,active,authorized,portal_access,can_manage&${eq("sk_id",profile.skId)}&limit=1`);
  }
  if((!rows||!rows.length)&&profile.email){
    rows=await sb(`agent_users?select=id,sk_id,email,active,authorized,portal_access,can_manage&${eq("email",profile.email)}&limit=1`);
  }
  const actor=rows?.[0]||null;
  if(!actor)throw new Error("Your Wix staff profile is not linked to Supabase agent_users.");
  if(actor.active===false||actor.authorized===false||actor.portal_access===false)throw new Error("Your Supabase staff account is not authorized for Inventory Control.");
  return{
    id:actor.id,
    skId:upper(actor.sk_id||profile.skId,40),
    name:profile.name||profile.email||profile.skId,
    email:clean(actor.email||profile.email,200).toLowerCase(),
    canManage:actor.can_manage===true
  };
}
async function requireStaff(){
  const s=await getStaffPortalSession();
  if(!s||s.ok===false||s.authorized===false||s.loggedIn===false)throw new Error("Inventory Control requires an authorized staff session.");
  const p=profileOf(s);
  if(!p.skId&&!p.email)throw new Error("A valid SK-ID or staff email is required.");
  return resolveSupabaseActor(p);
}

function apiRecord(r={}){return{id:r.id,publicId:r.public_id,entityType:r.entity_type,code:r.code,name:r.name,slug:r.slug||"",status:r.status,active:r.active,customerVisible:r.customer_visible,staffVisible:r.staff_visible,alteaVisible:r.altea_visible,featured:r.featured,homepageFeatured:r.homepage_featured,sortPriority:r.sort_priority,parentEntityId:r.parent_entity_id||"",supplierEntityId:r.supplier_entity_id||"",source:r.source||"SKANDI",sourceReference:r.source_reference||"",details:r.details||{},commercial:r.commercial||{},operations:r.operations||{},seo:r.seo||{},publication:r.publication||{},payload:r.payload||{},createdAt:r.created_at,updatedAt:r.updated_at}}
function apiLocalized(r={}){return{id:r.id,entityId:r.entity_id,language:r.language,title:r.title||"",eyebrow:r.eyebrow||"",shortDescription:r.short_description||"",fullDescription:r.full_description||"",highlights:r.highlights||[],included:r.included||[],notIncluded:r.not_included||[],importantInformation:r.important_information||"",seoTitle:r.seo_title||"",seoDescription:r.seo_description||"",content:r.content||{}}}
function apiMedia(r={}){return{id:r.id,entityId:r.entity_id,mediaType:r.media_type,url:r.url,altText:r.alt_text||"",caption:r.caption||"",credit:r.credit||"",language:r.language||"",sortOrder:r.sort_order,isPrimary:r.is_primary,isCard:r.is_card,isHero:r.is_hero,isMobile:r.is_mobile,active:r.active,payload:r.payload||{}}}
function apiRelation(r={}){return{id:r.id,sourceEntityId:r.source_entity_id,targetEntityId:r.target_entity_id,relationType:r.relation_type,sequenceNo:r.sequence_no,active:r.active,payload:r.payload||{}}}
function apiDated(r={}){return{id:r.id,entityId:r.entity_id,inventoryType:r.inventory_type,serviceDate:r.service_date,startTime:r.start_time||"",endTime:r.end_time||"",variantCode:r.variant_code||"",variantName:r.variant_name||"",capacityTotal:r.capacity_total,held:r.held,sold:r.sold,available:r.available,waitlistLimit:r.waitlist_limit,overbookingLimit:r.overbooking_limit,stopSale:r.stop_sale,blackout:r.blackout,status:r.status,supplierCost:Number(r.supplier_cost||0),publicPrice:Number(r.public_price||0),adultPrice:Number(r.adult_price||0),childPrice:Number(r.child_price||0),infantPrice:Number(r.infant_price||0),privatePrice:Number(r.private_price||0),currency:r.currency,priceBasis:r.price_basis,bookingCutoffHours:r.booking_cutoff_hours,minStay:r.min_stay,maxStay:r.max_stay,releaseDays:r.release_days,supplierReference:r.supplier_reference||"",payload:r.payload||{},createdAt:r.created_at,updatedAt:r.updated_at}}

function parseJsonValue(v,fallback=null){if(v===null||v===undefined||v==="")return fallback;if(typeof v==="object")return v;try{return JSON.parse(String(v))}catch(_e){return fallback===null?v:fallback}}
function jsonText(v){if(v===null||v===undefined||v==="")return null;return typeof v==="string"?v:JSON.stringify(v)}
function listValue(v){if(Array.isArray(v))return v;if(v===null||v===undefined||v==="")return[];const parsed=parseJsonValue(v,null);return Array.isArray(parsed)?parsed:[]}
function dateOnly(v){const s=clean(v,40);return /^\d{4}-\d{2}-\d{2}/.test(s)?s.slice(0,10):s}
function makeUuid(){if(globalThis.crypto&&typeof globalThis.crypto.randomUUID==="function")return globalThis.crypto.randomUUID();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==="x"?r:(r&3|8);return v.toString(16)})}
function referenceStatus(r={}){const s=upper(r.status,20);if(MASTER_STATUSES.has(s))return s;if(r.published===true)return"PUBLISHED";if(r.active===false)return"HIDDEN";return"DRAFT"}
function commonReferenceRecord(type,r,details){const isAirport=type==="AIRPORT";const id=clean(r.ID,120);const publicId=isAirport?clean(r.itemId||r.slug||r.iata||id,160):clean(r["Record ID"]||r.slug||r.iataCode||id,160);const code=isAirport?upper(r.iata,12):upper(r.iataCode,20);const name=isAirport?clean(r.title,240):clean(r.Title,240);return{id,publicId,entityType:type,code,name,slug:clean(r.slug||slugify(name),160),status:referenceStatus(r),active:bool(r.active,true),customerVisible:bool(r.customer_visible,Boolean(r.published)),staffVisible:bool(r.staff_visible,true),alteaVisible:bool(r.altea_visible,true),featured:bool(r.featured,false),homepageFeatured:bool(r.homepage_featured,false),sortPriority:int(r.sort_order??r.sortOrder,100),parentEntityId:"",supplierEntityId:"",source:clean(r.source||"SKANDI",80),sourceReference:clean(r.source_reference,500),details,commercial:object(r.commercial),operations:object(r.operations),seo:object(r.seo),publication:object(r.publication),payload:object(r.payload),createdAt:r.created_at||r["Created Date"]||null,updatedAt:r.updated_at||null,sourceTable:isAirport?TABLES.airports:TABLES.airlines}}
function apiAirport(r={}){const stored=object(r.inventory_details);return commonReferenceRecord("AIRPORT",r,{...stored,iata:upper(r.iata,12),icao:upper(r.icao,12),city:clean(r.locationCity,240),country:clean(r.country,160),timezone:clean(r.timezone,120),latitude:num(r.latitude,0),longitude:num(r.longitude,0),distanceToCityCenterKm:num(r.distanceToCityCenterKm,0),website:clean(r.website,2000),contactUrl:clean(r.contactUrl,2000),primaryColor:clean(r.primaryColor,40),accentColor:clean(r.accentColor,40),lastReviewed:dateOnly(r.lastReviewed),terminalsJson:listValue(r.terminalsJson),runwaysJson:listValue(r.runwaysJson),quickFactsJson:listValue(r.quickFactsJson),transportJson:listValue(r.transportJson),foodDrinksJson:listValue(r.foodDrinksJson),lostFoundJson:listValue(r.lostFoundJson),sourceUrlsJson:listValue(r.sourceUrlsJson),overview:clean(r.summary||r.body,10000),information:clean(r.information,20000),lounges:clean(r.lounges,20000),airportHotels:clean(r.airportHotels,10000),destinationsServing:clean(r.destinationsServing,10000),sectionsJson:listValue(r.sectionsJson),notes:clean(r.notes,20000),logoUrl:clean(r.logoUrl,2000),logoIconUrl:clean(r.logoIconUrl,2000),logoAltText:clean(r.logoAltText,1000),heroImageUrl:clean(r.heroImageUrl,2000)})}
function apiAirline(r={}){const stored=object(r.inventory_details);return commonReferenceRecord("AIRLINE",r,{...stored,iata:upper(r.iataCode,20),icao:upper(r.icaoCode,20),shortName:clean(r.shortName,240),alliance:clean(r.alliance,120),brandGroup:clean(r.brandGroup,160),country:clean(r.locationCountry,160),city:clean(r.locationCity,160),website:clean(r.website,2000),primaryColor:clean(r.primaryColor,40),accentColor:clean(r.accentColor,40),lastReviewed:dateOnly(r.lastReviewed),logoUrl:clean(r.logoFile,2000),logoIconUrl:clean(r.logoIcon,2000),logoAltText:clean(r.logoAltText,1000),heroImageUrl:clean(r.heroAircraftUrl,2000),hubsJson:parseJsonValue(r.hubsJson,[]),fleetSummaryJson:parseJsonValue(r.fleetSummaryJson,[]),aircraftFamiliesText:clean(r.aircraftFamiliesText,20000),aircraftConfigurationsJson:parseJsonValue(r.aircraftConfigurationsJson,[]),cabinsJson:parseJsonValue(r.cabinsJson,[]),quickFactsJson:parseJsonValue(r.quickFactsJson,[]),sourceUrlsJson:parseJsonValue(r.sourceUrlsJson,[]),checkInDeadline:clean(r.checkInDeadline,10000),boarding:clean(r.boarding,20000),baggageAllowance:clean(r.baggageAllowence,20000),classComparisonText:clean(r.classComparisonText,20000),foodDrinksJson:parseJsonValue(r.foodDrinksJson,[]),wifiOnboardJson:parseJsonValue(r.wifiOnboardJson,[]),lounges:clean(r.lounges,20000),loyaltyProgram:clean(r.loyaltyProgram,1000),loyaltyProgramUrl:clean(r.loyaltyProgramUrl,2000),delayCancellationJson:parseJsonValue(r.delayCancellationJson,[]),damagedBaggageJson:parseJsonValue(r.damagedBaggageJson,[]),lostFoundJson:parseJsonValue(r.lostFoundJson,[]),childrenInfantsJson:parseJsonValue(r.childrenInfantsJson,[]),ticketTypesJson:parseJsonValue(r.ticketTypesJson,[]),contactUrl:clean(r.contactUrl,2000),sectionsJson:parseJsonValue(r.sectionsJson,[]),notes:clean(r.notes,20000)})}
function referenceBundle(type,r){const record=type==="AIRPORT"?apiAirport(r):apiAirline(r);const localized=Array.isArray(r.localized_content)?r.localized_content:[];const media=Array.isArray(r.media_assets)?r.media_assets:[];const rel=Array.isArray(object(r.payload).inventoryRelations)?object(r.payload).inventoryRelations:[];return{record,localizedContent:localized,media,relations:rel}}
async function allAirportRows(){return await sb(`${TABLES.airports}?select=*&limit=2000`)||[]}
async function allAirlineRows(){return await sb(`${TABLES.airlines}?select=*&limit=2000`)||[]}
async function referenceRowById(id){if(!id)return null;let rows=await sb(`${TABLES.airports}?select=*&${eq("ID",id)}&limit=1`);if(rows?.[0])return{type:"AIRPORT",row:rows[0]};rows=await sb(`${TABLES.airlines}?select=*&${eq("ID",id)}&limit=1`);return rows?.[0]?{type:"AIRLINE",row:rows[0]}:null}
function refItem(record){return{id:record.id,publicId:record.publicId,entityType:record.entityType,code:record.code,name:record.name,slug:record.slug,status:record.status,active:record.active,details:record.details||{},sourceTable:record.sourceTable}}
function referenceFilter(records,input={}){const status=upper(input.status,20),search=clean(input.query,200).toLowerCase(),visible=input.customerVisible;return records.filter(r=>(!status||r.status===status)&&(!(visible==="true"||visible===true)||r.customerVisible===true)&&(!(visible==="false"||visible===false)||r.customerVisible===false)&&(!search||[r.publicId,r.entityType,r.code,r.name,r.slug,r.details?.city,r.details?.country].join(" ").toLowerCase().includes(search))).sort((a,b)=>(a.sortPriority-b.sortPriority)||String(a.name).localeCompare(String(b.name)))}
function referenceDefaults(record){const r=JSON.parse(JSON.stringify(record||{}));r.entityType=upper(r.entityType,40);if(!REFERENCE_TYPES.has(r.entityType))throw new Error("Unsupported reference entity type.");r.details=object(r.details);r.commercial=object(r.commercial);r.operations=object(r.operations);r.seo=object(r.seo);r.publication=object(r.publication);r.payload=object(r.payload);r.name=clean(r.name,240);r.slug=slugify(r.slug||r.name);r.status=MASTER_STATUSES.has(upper(r.status,20))?upper(r.status,20):"DRAFT";r.source=clean(r.source||"SKANDI",80)||"SKANDI";if(!r.name)throw new Error("Master Name / Title is required.");if(r.entityType==="AIRPORT"){r.details.iata=upper(r.details.iata||r.code,12);r.details.icao=upper(r.details.icao,12);r.code=r.details.iata;if(!r.details.iata)throw new Error("IATA Code is required.")}else{r.details.iata=upper(r.details.iata||r.code,20);r.details.icao=upper(r.details.icao,20);r.code=r.details.iata;if(!r.details.iata)throw new Error("Airline IATA Code is required.")}if(r.status==="PUBLISHED"){r.active=true;r.customerVisible=true}if(["ARCHIVED","SUSPENDED"].includes(r.status)){r.active=false;r.customerVisible=false}if(r.status!=="PUBLISHED")r.homepageFeatured=false;if(r.homepageFeatured){r.featured=true;r.customerVisible=true}return r}
function referencePayload(record,input={}){const p={...object(record.payload),inventoryRelations:Array.isArray(input.relations)?input.relations:[],smartInventoryVersion:"2026-09-07-reference-v1"};return{payload:p,localized_content:Array.isArray(input.localizedContent)?input.localizedContent:[],media_assets:Array.isArray(input.media)?input.media:[]}}
function dbAirport(record,input={}){const d=object(record.details),extra=referencePayload(record,input);return{title:record.name,slug:record.slug||null,active:record.active!==false,sort_order:int(record.sortPriority,100),iata:upper(d.iata||record.code,12)||null,icao:upper(d.icao,12)||null,country:clean(d.country,160)||null,locationCity:clean(d.city,240)||null,distanceToCityCenterKm:num(d.distanceToCityCenterKm,0),website:clean(d.website,2000)||null,summary:clean(d.overview,10000)||null,latitude:num(d.latitude,0),longitude:num(d.longitude,0),information:clean(d.information,20000)||null,quickFactsJson:Array.isArray(d.quickFactsJson)?d.quickFactsJson:[],transportJson:Array.isArray(d.transportJson)?d.transportJson:[],runwaysJson:Array.isArray(d.runwaysJson)?d.runwaysJson:[],terminalsJson:Array.isArray(d.terminalsJson)?d.terminalsJson:[],logoUrl:clean(d.logoUrl,2000)||null,logoIconUrl:clean(d.logoIconUrl,2000)||null,logoAltText:clean(d.logoAltText,1000)||null,heroImageUrl:clean(d.heroImageUrl,2000)||null,sourceUrlsJson:Array.isArray(d.sourceUrlsJson)?d.sourceUrlsJson:[],lounges:clean(d.lounges,20000)||null,foodDrinksJson:Array.isArray(d.foodDrinksJson)?d.foodDrinksJson:[],airportHotels:clean(d.airportHotels,10000)||null,lostFoundJson:Array.isArray(d.lostFoundJson)?d.lostFoundJson:[],destinationsServing:clean(d.destinationsServing,10000)||null,contactUrl:clean(d.contactUrl,2000)||null,sectionsJson:Array.isArray(d.sectionsJson)?d.sectionsJson:[],lastReviewed:d.lastReviewed||null,primaryColor:clean(d.primaryColor,40)||null,accentColor:clean(d.accentColor,40)||null,notes:clean(d.notes,20000)||null,status:record.status,customer_visible:bool(record.customerVisible,false),staff_visible:bool(record.staffVisible,true),altea_visible:bool(record.alteaVisible,true),featured:bool(record.featured,false),homepage_featured:bool(record.homepageFeatured,false),published:record.status==="PUBLISHED",source:record.source||"SKANDI",source_reference:clean(record.sourceReference,500)||null,timezone:clean(d.timezone,120)||null,inventory_details:d,commercial:object(record.commercial),operations:object(record.operations),seo:object(record.seo),publication:object(record.publication),...extra,...(record.publicId?{itemId:clean(record.publicId,160)}:{})}}
function dbAirline(record,input={},old=null){const d=object(record.details),extra=referencePayload(record,input);const id=clean(record.id||old?.ID,120)||makeUuid();return{"ID":id,"Title":record.name,"Record ID":clean(record.publicId||old?.["Record ID"]||record.slug,160)||null,slug:record.slug||null,shortName:clean(d.shortName,240)||null,alliance:clean(d.alliance,120)||null,brandGroup:clean(d.brandGroup,160)||null,locationCountry:clean(d.country,160)||null,locationCity:clean(d.city,160)||null,website:clean(d.website,2000)||null,quickFactsJson:d.quickFactsJson??[],primaryColor:clean(d.primaryColor,40)||null,accentColor:clean(d.accentColor,40)||null,notes:clean(d.notes,20000)||null,cabinsJson:jsonText(d.cabinsJson),logoFile:clean(d.logoUrl,2000)||null,logoIcon:clean(d.logoIconUrl,2000)||null,logoAltText:clean(d.logoAltText,1000)||null,heroAircraftUrl:clean(d.heroImageUrl,2000)||null,sourceUrlsJson:jsonText(d.sourceUrlsJson),checkInDeadline:clean(d.checkInDeadline,10000)||null,lounges:clean(d.lounges,20000)||null,classComparisonText:clean(d.classComparisonText,20000)||null,loyaltyProgram:clean(d.loyaltyProgram,1000)||null,loyaltyProgramUrl:clean(d.loyaltyProgramUrl,2000)||null,hubsJson:d.hubsJson??[],fleetSummaryJson:jsonText(d.fleetSummaryJson),aircraftFamiliesText:clean(d.aircraftFamiliesText,20000)||null,aircraftConfigurationsJson:jsonText(d.aircraftConfigurationsJson),boarding:clean(d.boarding,20000)||null,foodDrinksJson:jsonText(d.foodDrinksJson),wifiOnboardJson:jsonText(d.wifiOnboardJson),delayCancellationJson:jsonText(d.delayCancellationJson),damagedBaggageJson:jsonText(d.damagedBaggageJson),lostFoundJson:jsonText(d.lostFoundJson),childrenInfantsJson:jsonText(d.childrenInfantsJson),ticketTypesJson:jsonText(d.ticketTypesJson),baggageAllowence:clean(d.baggageAllowance,20000)||null,contactUrl:clean(d.contactUrl,2000)||null,sectionsJson:jsonText(d.sectionsJson),lastReviewed:d.lastReviewed||null,active:record.active!==false,iataCode:upper(d.iata||record.code,20)||null,icaoCode:upper(d.icao,20)||null,sort_order:int(record.sortPriority,100),status:record.status,customer_visible:bool(record.customerVisible,false),staff_visible:bool(record.staffVisible,true),altea_visible:bool(record.alteaVisible,true),featured:bool(record.featured,false),homepage_featured:bool(record.homepageFeatured,false),published:record.status==="PUBLISHED",source:record.source||"SKANDI",source_reference:clean(record.sourceReference,500)||null,inventory_details:d,commercial:object(record.commercial),operations:object(record.operations),seo:object(record.seo),publication:object(record.publication),...extra}}
async function saveReferenceRecord(p,input={}){const raw=referenceDefaults(applyStructures(object(input.record),input.structures));const id=clean(raw.id,120);let old=null;if(id){const found=await referenceRowById(id);if(!found||found.type!==raw.entityType)throw new Error(`${raw.entityType} record no longer exists.`);old=found.row}const table=raw.entityType==="AIRPORT"?TABLES.airports:TABLES.airlines;const body=raw.entityType==="AIRPORT"?dbAirport(raw,input):dbAirline(raw,input,old);const savedRows=old?await sb(`${table}?${eq("ID",old.ID)}`,{method:"PATCH",body}):await sb(table,{method:"POST",body});const saved=savedRows?.[0];if(!saved)throw new Error("Supabase did not return the saved reference record.");const normalized=raw.entityType==="AIRPORT"?apiAirport(saved):apiAirline(saved);try{await sb(TABLES.audit,{method:"POST",body:{event_type:old?"REFERENCE_UPDATED":"REFERENCE_CREATED",domain:"MASTER_INVENTORY",entity_table:table,entity_id:normalized.id,product_key:normalized.publicId||normalized.code,source:"wix-smart-inventory",message:`${raw.entityType} ${normalized.code} ${old?"updated":"created"} in ${table}.`,payload:{sourceTable:table,code:normalized.code,status:normalized.status},created_by_agent_user_id:p.id||null,created_by_name:p.name||p.skId}})}catch(_e){}return{record:normalized,bundle:referenceBundle(raw.entityType,saved)}}

async function refs(){const[rows,airports,airlines]=await Promise.all([sb(`${TABLES.master}?select=id,public_id,entity_type,code,name,slug,status,active,details&order=entity_type.asc,name.asc&limit=2000`),allAirportRows(),allAirlineRows()]);const master=(rows||[]).filter(r=>!REFERENCE_TYPES.has(r.entity_type)).map(r=>({id:r.id,publicId:r.public_id,entityType:r.entity_type,code:r.code,name:r.name,slug:r.slug,status:r.status,active:r.active,details:r.details||{}}));return[...master,...airports.map(r=>refItem(apiAirport(r))),...airlines.map(r=>refItem(apiAirline(r)))].sort((a,b)=>String(a.entityType).localeCompare(String(b.entityType))||String(a.name).localeCompare(String(b.name)))}
async function lookup(id){if(!id)return null;const rows=await sb(`${TABLES.master}?select=*&${eq("id",id)}&limit=1`);return rows?.[0]||null}
async function airportIata(id){if(!id)return"";const rows=await sb(`${TABLES.airports}?select=ID,iata&${eq("ID",id)}&limit=1`);return upper(rows?.[0]?.iata,12)}

const STRUCT={facts:[["label"],["value"]],faqs:[["question"],["answer"]],climate:[["month"],["avg_low_c","number"],["avg_high_c","number"],["daylight_hours","number"],["precipitation_mm","number"]],signature:[["title"],["description"]],rooms:[["code"],["name"],["roomType"],["maxGuests","number"],["bedType"],["sizeSqm","number"],["description"]],itinerary:[["sequence","number"],["stopName"],["durationMinutes","number"],["description"],["latitude","number"],["longitude","number"]],pickups:[["name"],["hotelId"],["timeOffsetMinutes","number"],["instructions"]],zones:[["code"],["name"],["durationMinutes","number"],["distanceKm","number"],["price","number"],["currency"]],sourceUrls:[["label"],["url"]],quickFacts:[["label"],["value"]],hubs:[["iata"],["name"]],fleet:[["aircraft"],["count","number"],["notes"]]};
function cleanRows(v,schema){return(Array.isArray(v)?v:[]).slice(0,200).map(row=>{const o={};for(const[k,t]of schema)o[k]=t==="number"?num(row?.[k],0):clean(row?.[k],5000);return o}).filter(o=>Object.values(o).some(v=>v!==""&&v!==null&&v!==undefined))}
function applyStructures(record,s={}){const d={...object(record.details)},o={...object(record.operations)};if(s.facts)d.facts=cleanRows(s.facts,STRUCT.facts);if(s.quickFacts){const x=cleanRows(s.quickFacts,STRUCT.quickFacts);d.pageFacts=x;d.quickFactsJson=x}if(s.faqs)d.faqs=cleanRows(s.faqs,STRUCT.faqs);if(s.climate)d.climate=cleanRows(s.climate,STRUCT.climate);if(s.signature)d.signature=cleanRows(s.signature,STRUCT.signature);if(s.rooms)d.rooms=cleanRows(s.rooms,STRUCT.rooms);if(s.sourceUrls)d.sourceUrlsJson=cleanRows(s.sourceUrls,STRUCT.sourceUrls);if(s.hubs)d.hubsJson=cleanRows(s.hubs,STRUCT.hubs);if(s.fleet)d.fleetSummaryJson=cleanRows(s.fleet,STRUCT.fleet);if(s.itinerary)o.itinerary=cleanRows(s.itinerary,STRUCT.itinerary);if(s.pickups)o.pickups=cleanRows(s.pickups,STRUCT.pickups);if(s.zones)o.transferZones=cleanRows(s.zones,STRUCT.zones);for(const k of ["goodFor","tags","facilities","languages","boardOptions","aircraftFamilies"])if(s[k])d[k]=arr(s[k]).slice(0,200);return{...record,details:d,operations:o}}

async function smartDefaults(r){const x=JSON.parse(JSON.stringify(r));x.details=object(x.details);x.commercial=object(x.commercial);x.operations=object(x.operations);x.seo=object(x.seo);x.code=upper(x.code,80);x.name=clean(x.name,240);x.slug=slugify(x.slug||x.name);x.source=clean(x.source||"SKANDI",80)||"SKANDI";if(!x.code)throw new Error("System Code is required.");if(!x.name)throw new Error("Master Name / Title is required.");if(!ENTITY_TYPES.has(x.entityType))throw new Error("Unsupported inventory entity type.");
 if(x.entityType==="DESTINATION"){x.details.level=upper(x.details.level||"DESTINATION",20);const p=await lookup(x.parentEntityId);if(p?.entity_type==="DESTINATION"){const pd=object(p.details);for(const k of["countryCode","countryName","currency","languages","drivingSide","electricalPlug","emergencyNumber","passportSummary","visaSummary"])if(x.details[k]===undefined||x.details[k]===null||x.details[k]===""||(Array.isArray(x.details[k])&&!x.details[k].length))if(pd[k]!==undefined&&pd[k]!==null&&pd[k]!=="")x.details[k]=pd[k]}if(!x.details.searchAirportIata&&x.details.nearestAirportId)x.details.searchAirportIata=await airportIata(x.details.nearestAirportId)}
 if(x.entityType==="AIRPORT"){x.details.iata=upper(x.details.iata||(x.code.length===3?x.code:""),3);x.details.icao=upper(x.details.icao,4)}if(x.entityType==="AIRLINE"){x.details.iata=upper(x.details.iata||(x.code.length===2?x.code:""),2);x.details.icao=upper(x.details.icao,3)}if(x.entityType==="HOTEL"&&!x.details.searchAirportIata&&x.details.nearestAirportId)x.details.searchAirportIata=await airportIata(x.details.nearestAirportId);
 if(x.entityType==="PACKAGE"){const a=safeDate(x.details.startDate),b=safeDate(x.details.endDate);if(a&&b){const days=Math.max(1,Math.round((new Date(b+"T12:00:00Z")-new Date(a+"T12:00:00Z"))/86400000)+1);x.details.numberOfDays=days;x.details.numberOfNights=Math.max(0,days-1)}}
 x.commercial.currency=upper(x.commercial.currency||"USD",3);x.commercial.supplierCost=Math.max(0,num(x.commercial.supplierCost,0));x.commercial.publicPrice=Math.max(0,num(x.commercial.publicPrice,0));x.commercial.marginPct=x.commercial.publicPrice>0?Math.round(((x.commercial.publicPrice-x.commercial.supplierCost)/x.commercial.publicPrice)*10000)/100:0;x.seo.canonicalSlug=x.seo.canonicalSlug||x.slug;x.seo.title=x.seo.title||x.name;x.seo.ogTitle=x.seo.ogTitle||x.name;if(x.seo.indexable===undefined)x.seo.indexable=true;x.status=MASTER_STATUSES.has(upper(x.status,20))?upper(x.status,20):"DRAFT";if(x.status==="PUBLISHED")x.active=true;if(["ARCHIVED","SUSPENDED"].includes(x.status)){x.active=false;x.customerVisible=false}if(x.entityType==="SUPPLIER"){x.customerVisible=false;x.featured=false;x.homepageFeatured=false;x.seo.indexable=false}if(x.status!=="PUBLISHED")x.homepageFeatured=false;if(x.homepageFeatured){x.featured=true;x.customerVisible=true}return x}
function dbMaster(r,p,old=null){const pub={...object(r.publication)};if(r.status==="PUBLISHED"&&(!old||old.status!=="PUBLISHED")){pub.publishedAt=new Date().toISOString();pub.publishedBy=p.id||p.skId}return{...(r.publicId?{public_id:clean(r.publicId,160)}:{}),entity_type:r.entityType,code:r.code,name:r.name,slug:r.slug||null,status:r.status,active:r.active!==false,customer_visible:bool(r.customerVisible,false),staff_visible:bool(r.staffVisible,true),altea_visible:bool(r.alteaVisible,true),featured:bool(r.featured,false),homepage_featured:bool(r.homepageFeatured,false),sort_priority:int(r.sortPriority,100),parent_entity_id:r.parentEntityId||null,supplier_entity_id:r.supplierEntityId||null,source:r.source||"SKANDI",source_reference:clean(r.sourceReference,500)||null,details:object(r.details),commercial:object(r.commercial),operations:object(r.operations),seo:object(r.seo),publication:pub,payload:{...object(r.payload),smartInventoryVersion:"2026-09-05-v4"},updated_by_agent_user_id:p.id||null,...(old?{}:{created_by_agent_user_id:p.id||null})}}
async function audit(p,type,id,message,payload={}){try{await sb(TABLES.audit,{method:"POST",body:{event_type:type,domain:"MASTER_INVENTORY",entity_table:TABLES.master,entity_id:id||null,product_key:payload.publicId||payload.code||null,source:"wix-smart-inventory",message,payload,created_by_agent_user_id:p.id||null,created_by_name:p.name||p.skId}})}catch(_e){}}
async function replaceLocalized(id,rows=[]){await sb(`${TABLES.localized}?${eq("entity_id",id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});const body=rows.filter(x=>LANGUAGES.includes(upper(x.language,2))).map(x=>({entity_id:id,language:upper(x.language,2),title:clean(x.title,500)||null,eyebrow:clean(x.eyebrow,500)||null,short_description:clean(x.shortDescription,5000)||null,full_description:clean(x.fullDescription,20000)||null,highlights:arr(x.highlights),included:arr(x.included),not_included:arr(x.notIncluded),important_information:clean(x.importantInformation,10000)||null,seo_title:clean(x.seoTitle,500)||null,seo_description:clean(x.seoDescription,2000)||null,content:object(x.content)}));if(body.length)await sb(TABLES.localized,{method:"POST",body})}
async function replaceMedia(id,rows=[]){await sb(`${TABLES.media}?${eq("entity_id",id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});const body=rows.filter(x=>clean(x.url,2000)).map((x,i)=>({entity_id:id,media_type:upper(x.mediaType||"IMAGE",30),url:clean(x.url,2000),alt_text:clean(x.altText,1000)||null,caption:clean(x.caption,3000)||null,credit:clean(x.credit,500)||null,language:LANGUAGES.includes(upper(x.language,2))?upper(x.language,2):null,sort_order:int(x.sortOrder,(i+1)*10),is_primary:bool(x.isPrimary,false),is_card:bool(x.isCard,false),is_hero:bool(x.isHero,false),is_mobile:bool(x.isMobile,false),active:bool(x.active,true),payload:object(x.payload)}));if(body.length)await sb(TABLES.media,{method:"POST",body})}
async function replaceRelations(id,rows=[]){await sb(`${TABLES.relations}?${eq("source_entity_id",id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});const body=rows.filter(x=>x.targetEntityId&&x.relationType&&x.targetEntityId!==id).map((x,i)=>({source_entity_id:id,target_entity_id:x.targetEntityId,relation_type:upper(x.relationType,80),sequence_no:int(x.sequenceNo,(i+1)*10),active:bool(x.active,true),payload:object(x.payload)}));if(body.length)await sb(TABLES.relations,{method:"POST",body})}
async function bundle(id){const rows=await sb(`${TABLES.master}?select=*&${eq("id",id)}&limit=1`),r=rows?.[0];if(r){const[l,m,rel]=await Promise.all([sb(`${TABLES.localized}?select=*&${eq("entity_id",id)}&order=language.asc`),sb(`${TABLES.media}?select=*&${eq("entity_id",id)}&order=sort_order.asc`),sb(`${TABLES.relations}?select=*&${eq("source_entity_id",id)}&order=sequence_no.asc`)]);return{record:apiRecord(r),localizedContent:(l||[]).map(apiLocalized),media:(m||[]).map(apiMedia),relations:(rel||[]).map(apiRelation)}}const ref=await referenceRowById(id);if(ref)return referenceBundle(ref.type,ref.row);throw new Error("Inventory record not found.")}

export const getSmartInventoryBootstrap=webMethod(Permissions.SiteMember,async(input={})=>{const p=await requireStaff();const type=upper(input.entityType,40);let records=[];if(type==="AIRPORT"){records=referenceFilter((await allAirportRows()).map(apiAirport),input)}else if(type==="AIRLINE"){records=referenceFilter((await allAirlineRows()).map(apiAirline),input)}else{const f=["select=*"];if(type&&ENTITY_TYPES.has(type))f.push(eq("entity_type",type));if(input.status&&MASTER_STATUSES.has(upper(input.status,20)))f.push(eq("status",upper(input.status,20)));if(input.customerVisible==="true"||input.customerVisible===true)f.push("customer_visible=eq.true");if(input.customerVisible==="false"||input.customerVisible===false)f.push("customer_visible=eq.false");f.push("order=sort_priority.asc,name.asc","limit=2000");let rows=await sb(`${TABLES.master}?${f.join("&")}`);if(!type)rows=(rows||[]).filter(r=>!REFERENCE_TYPES.has(r.entity_type));const search=clean(input.query,200).toLowerCase();if(search)rows=(rows||[]).filter(r=>[r.public_id,r.entity_type,r.code,r.name,r.slug].join(" ").toLowerCase().includes(search));records=(rows||[]).map(apiRecord);if(!type){const[a,b]=await Promise.all([allAirportRows(),allAirlineRows()]);records=[...records,...referenceFilter(a.map(apiAirport),input),...referenceFilter(b.map(apiAirline),input)]}}return{session:p,records,references:await refs(),lastSync:new Date().toISOString(),sources:{AIRPORT:TABLES.airports,AIRLINE:TABLES.airlines,DEFAULT:TABLES.master}}});
export const getSmartInventoryRecord=webMethod(Permissions.SiteMember,async({id}={})=>{await requireStaff();return bundle(clean(id,120))});
export const saveSmartInventoryRecord=webMethod(Permissions.SiteMember,async(input={})=>{const p=await requireStaff();const entityType=upper(input?.record?.entityType,40);if(REFERENCE_TYPES.has(entityType))return saveReferenceRecord(p,input);let r=applyStructures(object(input.record),input.structures);r=await smartDefaults(r);const id=clean(r.id,100);let old=null;if(id){const rows=await sb(`${TABLES.master}?select=*&${eq("id",id)}&limit=1`);old=rows?.[0]||null;if(!old)throw new Error("Inventory master record no longer exists.")}const body=dbMaster(r,p,old);const savedRows=old?await sb(`${TABLES.master}?${eq("id",old.id)}`,{method:"PATCH",body}):await sb(TABLES.master,{method:"POST",body});const saved=savedRows?.[0];if(!saved?.id)throw new Error("Supabase did not return the saved master record.");await Promise.all([replaceLocalized(saved.id,input.localizedContent||[]),replaceMedia(saved.id,input.media||[]),replaceRelations(saved.id,input.relations||[])]);await audit(p,old?"MASTER_UPDATED":"MASTER_CREATED",saved.id,`${saved.entity_type} ${saved.code} ${old?"updated":"created"}.`,{publicId:saved.public_id,code:saved.code,status:saved.status});return{record:apiRecord(saved),bundle:await bundle(saved.id)}});
export const getSmartDatedInventory=webMethod(Permissions.SiteMember,async({entityId}={})=>{await requireStaff();const id=clean(entityId,100),rows=await sb(`${TABLES.dated}?select=*&${eq("entity_id",id)}&order=service_date.asc,start_time.asc,variant_code.asc&limit=2000`);return{inventory:(rows||[]).map(apiDated),lastSync:new Date().toISOString()}});
function dbDated(r,p){const total=Math.max(0,int(r.capacityTotal,0)),held=Math.max(0,int(r.held,0)),sold=Math.max(0,int(r.sold,0)),ob=Math.max(0,int(r.overbookingLimit,0)),available=Math.max(0,total+ob-held-sold);let status=DATED_STATUSES.has(upper(r.status,20))?upper(r.status,20):"OPEN";if(bool(r.blackout,false))status="BLACKOUT";else if(bool(r.stopSale,false))status="STOP_SALE";else if(total>0&&available===0)status="SOLD_OUT";else if(["BLACKOUT","STOP_SALE","SOLD_OUT"].includes(status))status="OPEN";const adult=Math.max(0,num(r.adultPrice,0)),pub=Math.max(0,num(r.publicPrice,adult));return{entity_id:clean(r.entityId,100),inventory_type:upper(r.inventoryType||"GENERAL",50),service_date:safeDate(r.serviceDate),start_time:safeTime(r.startTime),end_time:safeTime(r.endTime),variant_code:upper(r.variantCode,80)||null,variant_name:clean(r.variantName,240)||null,capacity_total:total,held,sold,available,waitlist_limit:Math.max(0,int(r.waitlistLimit,0)),overbooking_limit:ob,stop_sale:bool(r.stopSale,false),blackout:bool(r.blackout,false),status,supplier_cost:Math.max(0,num(r.supplierCost,0)),public_price:pub,adult_price:adult,child_price:Math.max(0,num(r.childPrice,0)),infant_price:Math.max(0,num(r.infantPrice,0)),private_price:Math.max(0,num(r.privatePrice,0)),currency:upper(r.currency||"USD",3),price_basis:upper(r.priceBasis||"PER_PERSON",40),booking_cutoff_hours:Math.max(0,int(r.bookingCutoffHours,0)),min_stay:Math.max(0,int(r.minStay,0)),max_stay:Math.max(0,int(r.maxStay,0)),release_days:Math.max(0,int(r.releaseDays,0)),supplier_reference:clean(r.supplierReference,500)||null,payload:{...object(r.payload),calculatedAvailable:available,smartInventoryVersion:"2026-09-05-v4"},updated_by_agent_user_id:p.id||null,...(r.id?{}:{created_by_agent_user_id:p.id||null})}}
export const saveSmartDatedInventory=webMethod(Permissions.SiteMember,async({row}={})=>{const p=await requireStaff();if(!row?.entityId)throw new Error("Master inventory entity is required.");if(!safeDate(row.serviceDate))throw new Error("Service Date is required.");const body=dbDated(row,p),savedRows=row.id?await sb(`${TABLES.dated}?${eq("id",row.id)}`,{method:"PATCH",body}):await sb(TABLES.dated,{method:"POST",body}),saved=savedRows?.[0];await audit(p,"DATED_INVENTORY_SAVED",row.entityId,`Dated inventory saved for ${row.serviceDate}.`,{entityId:row.entityId,inventoryId:saved?.id,status:saved?.status,available:saved?.available});return{row:apiDated(saved)}});
export const deleteSmartDatedInventory=webMethod(Permissions.SiteMember,async({id}={})=>{const p=await requireStaff(),rowId=clean(id,100),old=await sb(`${TABLES.dated}?select=*&${eq("id",rowId)}&limit=1`);await sb(`${TABLES.dated}?${eq("id",rowId)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});await audit(p,"DATED_INVENTORY_DELETED",old?.[0]?.entity_id||null,"Dated inventory row deleted.",{inventoryId:rowId});return{deleted:true,id:rowId}});
export const getSmartInventoryAudit=webMethod(Permissions.SiteMember,async(input={})=>{await requireStaff();const rows=await sb(`${TABLES.audit}?select=*&order=created_at.desc&limit=500`),d=clean(input.domain,80).toLowerCase(),k=clean(input.productKey,120).toLowerCase(),filtered=(rows||[]).filter(r=>(!d||String(r.domain||"").toLowerCase().includes(d))&&(!k||String(r.product_key||"").toLowerCase().includes(k)));return{audit:filtered.map(r=>({id:r.id,eventType:r.event_type,domain:r.domain,entityTable:r.entity_table,entityId:r.entity_id,productKey:r.product_key,message:r.message,agentName:r.created_by_name,timestamp:r.created_at,payload:r.payload||{}}))}});
