import { webMethod, Permissions } from "wix-web-module";
import { getSecret } from "wix-secrets-backend";
import { fetch } from "wix-fetch";

const LANGUAGES=["EN","SV","NO","DA","ES","FI","DE","FR-FR","FR-CA","TH"];
const ALIASES={"karon-beach":"karon","kata-beach":"kata","patong-beach":"patong","kamala-beach":"kamala","bangtao-beach":"bangtao","nai-yang-beach":"nai-yang"};
const FALLBACK=new Set(["thailand/phuket/karon","thailand/phuket/kata","thailand/phuket/patong","thailand/phuket/kamala","thailand/phuket/bangtao","thailand/phuket/nai-yang","greece/crete/chania","greece/crete/rethymnon","greece/crete/hersonissos","greece/crete/agios-nikolaos","spain/mallorca/palma","spain/mallorca/alcudia","spain/mallorca/cala-dor","spain/mallorca/palma-nova"]);
function clean(value,fallback){return String(value||fallback).trim().toLowerCase().replace(/[^a-z0-9-]/g,"")||fallback} function cleanArea(value){const slug=clean(value,"karon");return ALIASES[slug]||slug} function locale(value){const v=String(value||"EN").trim().toUpperCase();return LANGUAGES.includes(v)?v:"EN"} function obj(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}} function translation(v){if(!v||typeof v!=="object"||Array.isArray(v))return false;const keys=Object.keys(v);return keys.length>0&&keys.every(k=>LANGUAGES.includes(k))} function localize(v,l){if(Array.isArray(v))return v.map(x=>localize(x,l));if(!v||typeof v!=="object")return v;if(translation(v))return v[l]??v.EN??v.SV??Object.values(v)[0]??"";return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,localize(x,l)]))}
async function config(){const[url,key]=await Promise.all([getSecret("SUPABASE_URL"),getSecret("SUPABASE_SERVICE_ROLE_KEY")]);return{url:String(url||"").replace(/\/$/,""),key:String(key||"")}} async function get(path){const c=await config();if(!c.url||!c.key)throw new Error("Supabase hotel-search content is not configured.");const response=await fetch(`${c.url}/rest/v1/${path}`,{method:"get",headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,Accept:"application/json"}});if(!response.ok){const detail=await response.text();throw new Error(`Supabase hotel-search request failed (${response.status}): ${detail.slice(0,280)}`)}return response.json()}
async function load(countrySlug,destinationSlug,areaSlug){const query=["area_hotel_search_pages",`?country_slug=eq.${encodeURIComponent(countrySlug)}`,`&destination_slug=eq.${encodeURIComponent(destinationSlug)}`,`&area_slug=eq.${encodeURIComponent(areaSlug)}`,"&is_published=eq.true","&select=country_slug,destination_slug,area_slug,country_code,country_names,destination_names,area_names,hero_image,intro,preview_hotels,updated_at","&limit=1"].join("");const rows=await get(query);return Array.isArray(rows)?rows[0]||null:null}
export const getAreaHotelSearchPage=webMethod(Permissions.Anyone,async(input={})=>{const countrySlug=clean(input.countrySlug,"thailand"),destinationSlug=clean(input.destinationSlug,"phuket"),areaSlug=cleanArea(input.areaSlug),language=locale(input.language||input.locale),route=`${countrySlug}/${destinationSlug}/${areaSlug}`;try{const row=await load(countrySlug,destinationSlug,areaSlug);if(!row)return{clientFallback:true,countrySlug:FALLBACK.has(route)?countrySlug:"thailand",destinationSlug:FALLBACK.has(route)?destinationSlug:"phuket",areaSlug:FALLBACK.has(route)?areaSlug:"karon"};return{page:{countrySlug:row.country_slug,destinationSlug:row.destination_slug,areaSlug:row.area_slug,slug:row.area_slug,countryCode:row.country_code,countryName:localize(obj(row.country_names),language)||row.country_slug,destinationName:localize(obj(row.destination_names),language)||row.destination_slug,name:localize(obj(row.area_names),language)||row.area_slug,heroImage:row.hero_image||"",intro:localize(row.intro,language)||"",previewHotels:localize(Array.isArray(row.preview_hotels)?row.preview_hotels:[],language),updatedAt:row.updated_at}}}catch(error){console.warn(`[AreaHotelSearchService] Falling back to embedded ${route}.`,error);return{clientFallback:true,countrySlug:FALLBACK.has(route)?countrySlug:"thailand",destinationSlug:FALLBACK.has(route)?destinationSlug:"phuket",areaSlug:FALLBACK.has(route)?areaSlug:"karon"}}});
