import { webMethod, Permissions } from "wix-web-module";
import { getSecret } from "wix-secrets-backend";
import { fetch } from "wix-fetch";

const LANGUAGES = ["EN","SV","NO","DA"];
const CURRENCIES = ["USD","SEK","NOK","DKK","EUR"];
function cleanLanguage(value) { const v = String(value || "EN").toUpperCase(); return LANGUAGES.includes(v) ? v : "EN"; }
function cleanCurrency(value) { const v = String(value || "USD").toUpperCase(); return CURRENCIES.includes(v) ? v : "USD"; }
function localize(value, language) { if (Array.isArray(value)) return value.map(item => localize(item, language)); if (!value || typeof value !== "object") return value; const keys = Object.keys(value); if (keys.length && keys.every(key => LANGUAGES.includes(key))) return value[language] ?? value.EN ?? Object.values(value)[0] ?? ""; return Object.fromEntries(Object.entries(value).map(([key,item]) => [key,localize(item,language)])); }
async function config() { const [url,key] = await Promise.all([getSecret("SUPABASE_URL"),getSecret("SUPABASE_SERVICE_ROLE_KEY")]); return { url: String(url || "").replace(/\/$/,""), key: String(key || "") }; }
async function sb(path, options = {}) { const c = await config(); if (!c.url || !c.key) throw new Error("Supabase Tours & Activities content is not configured."); const response = await fetch(`${c.url}/rest/v1/${path}`, { method: options.method || "get", headers: { apikey:c.key, Authorization:`Bearer ${c.key}`, Accept:"application/json", "Content-Type":"application/json", Prefer: options.prefer || "return=representation" }, body: options.body ? JSON.stringify(options.body) : undefined }); if (!response.ok) throw new Error(`Tours data request failed (${response.status}): ${(await response.text()).slice(0,240)}`); const text = await response.text(); return text ? JSON.parse(text) : null; }
function mapDestination(row, language) { return { id:row.destination_slug, country:row.country_slug, name:localize(row.names,language), count:Number(row.activity_count || 0), image:row.image_url || "", latitude:Number(row.latitude || 0), longitude:Number(row.longitude || 0) }; }
function mapActivity(row, language, currency) { return { id:row.activity_slug, providerId:row.provider_id || "", destination:row.destination_slug, category:row.category || "activities", title:localize(row.title,language), description:localize(row.description,language), image:row.hero_image || "", gallery:Array.isArray(row.gallery) ? row.gallery : [], rating:Number(row.rating || 0), reviews:Number(row.review_count || 0), duration:localize(row.duration_label,language) || row.duration_code || "", durationCode:row.duration_code || "half", price:row.preview_price === null ? null : Number(row.preview_price), currency:row.preview_currency || currency, languages:Array.isArray(row.languages) ? row.languages : ["EN"], freeCancellation:Boolean(row.free_cancellation), pickup:Boolean(row.hotel_pickup), instant:Boolean(row.instant_confirmation), accessible:Boolean(row.accessibility_info), collection:row.collection || "", providerName:row.provider_name || "SKANDI Experiences", highlights:localize(row.highlights,language) || [], itinerary:localize(row.itinerary,language) || [], included:localize(row.included,language) || [], notIncluded:localize(row.not_included,language) || [], meeting:localize(row.meeting_information,language) || "", cancellation:localize(row.cancellation_policy,language) || "", live:Boolean(row.is_live), providerPayload:row.provider_payload || {} }; }
async function staticDestinations(language) { const rows = await sb("tour_activity_destinations?is_published=eq.true&select=*&order=sort_order.asc,destination_slug.asc"); return (rows || []).map(row => mapDestination(row,language)); }
async function staticActivities(language,currency,filters={}) { const parts=["tour_activity_products?is_published=eq.true","&select=*","&order=featured.desc,rating.desc,review_count.desc","&limit=200"]; if(filters.destinationId)parts.push(`&destination_slug=eq.${encodeURIComponent(filters.destinationId)}`); if(filters.category && filters.category !== "all")parts.push(`&category=eq.${encodeURIComponent(filters.category)}`); const rows=await sb(parts.join("")); return (rows || []).map(row=>mapActivity(row,language,currency)); }

export const getToursActivitiesBootstrap = webMethod(Permissions.Anyone, async input => { const language=cleanLanguage(input.language), currency=cleanCurrency(input.currency); try { const [destinations,experiences]=await Promise.all([staticDestinations(language),staticActivities(language,currency)]); return { destinations, experiences, source:"SUPABASE" }; } catch (error) { console.warn("[ToursActivities] Client fallback used.", error); return { destinations:[], experiences:[], source:"CLIENT_FALLBACK" }; } });
export const searchToursActivities = webMethod(Permissions.Anyone, async input => { const language=cleanLanguage(input.language), currency=cleanCurrency(input.currency); /* Replace or augment this call with a live provider adapter when selected. */ const items=await staticActivities(language,currency,input); return { ok:true, items, source:"SUPABASE_PREVIEW", live:false }; });
export const getTourActivityDetail = webMethod(Permissions.Anyone, async input => { const language=cleanLanguage(input.language), currency=cleanCurrency(input.currency), id=String(input.activityId || "").trim(); if(!id)throw new Error("Activity ID is required."); const rows=await sb(`tour_activity_products?activity_slug=eq.${encodeURIComponent(id)}&is_published=eq.true&select=*&limit=1`); if(!rows?.[0])throw new Error("The requested experience was not found."); return { activity:mapActivity(rows[0],language,currency) }; });
export const searchNearbyToursActivities = webMethod(Permissions.Anyone, async input => { const language=cleanLanguage(input.language), currency=cleanCurrency(input.currency), latitude=Number(input.latitude), longitude=Number(input.longitude); if(!Number.isFinite(latitude)||!Number.isFinite(longitude))throw new Error("Valid coordinates are required."); const destinations=await staticDestinations(language); const ranked=destinations.map(d=>({ ...d, distance:Math.hypot((d.latitude-latitude)*111,(d.longitude-longitude)*85) })).sort((a,b)=>a.distance-b.distance); const nearest=ranked[0]; if(!nearest)return { items:[], locationName:"" }; const items=await staticActivities(language,currency,{destinationId:nearest.id}); return { items, locationName:nearest.name, destinationId:nearest.id }; });
export const createTourActivityBookingCart = webMethod(Permissions.Anyone, async input => { const activity=input.activity || {}, selection=input.selection || {}; if(!activity.id)throw new Error("Activity data is required."); if(!activity.live)return { ok:false, live:false, message:"Live experience checkout is not connected yet." }; const cartId=`EXP-${Date.now()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`; const rows=await sb("tour_activity_carts",{method:"post",body:{cart_id:cartId,activity_slug:activity.id,provider_id:activity.providerId || null,selection,provider_payload:activity.providerPayload || {},currency:cleanCurrency(input.currency),status:"Created",created_at:new Date().toISOString(),updated_at:new Date().toISOString()}}); return { ok:true, cartId, checkoutPath:`/booking?step=experiences&cartId=${encodeURIComponent(cartId)}`, cart:rows?.[0] || null }; });
